-- Preparing database for autogenerated INSERTs.

-- Drops the old tables.
DROP TABLE IF EXISTS contexts_new;
DROP TABLE IF EXISTS books_genres_new;
DROP TABLE IF EXISTS books_authors_new;
DROP TABLE IF EXISTS genres_new;
DROP TABLE IF EXISTS books_new;
DROP TABLE IF EXISTS authors_new;

-- Creates the necessary tables to be used by autogenerated inserts.
CREATE TABLE authors_new (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (name)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_latvian_ci;

CREATE TABLE genres_new (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL,
  subgenre bool NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (name)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_latvian_ci;

CREATE TABLE books_new (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  full_source varchar(50) NOT NULL,
  collection_code varchar(40),
  item_code varchar(40),
  name varchar(100) NOT NULL,
  year1 smallint unsigned NOT NULL,
  year2 smallint unsigned NOT NULL,
  pub_century tinyint unsigned NOT NULL,
  index_type enum('GNP', 'GLR', 'LR', 'P'),
  manuscript boolean,
  order_in_collection tinyint unsigned DEFAULT 0,
  
  PRIMARY KEY (id),
  UNIQUE (full_source),
  INDEX (full_source)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_latvian_ci;

CREATE TABLE books_genres_new (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  source varchar(50) NOT NULL,
  genre_id smallint unsigned NOT NULL,

  PRIMARY KEY (id),
  FOREIGN KEY (source) REFERENCES books_new(full_source),
  FOREIGN KEY (genre_id) REFERENCES genres_new(id)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_latvian_ci;

CREATE TABLE books_authors_new (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  source varchar(50) NOT NULL,
  author_id smallint unsigned NOT NULL,
  top_author boolean,

  PRIMARY KEY (id),
  FOREIGN KEY (source) REFERENCES books_new(full_source),
  FOREIGN KEY (author_id) REFERENCES authors_new(id)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_latvian_ci;


CREATE TABLE contexts_new (
  id int unsigned NOT NULL AUTO_INCREMENT,
  source varchar(50) NOT NULL,
  adress varchar(100),
  page varchar(40),
  html_line_order smallint unsigned NOT NULL,
  data_html text NOT NULL,
  data_plain text NOT NULL,

  PRIMARY KEY (id),
  FOREIGN KEY (source) REFERENCES books_new(full_source),
  INDEX (source),
  INDEX (adress),
  INDEX (page)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_latvian_ci;
