-- Preparing database for autogenerated INSERTs.

-- Drops the old tables.
DROP TABLE IF EXISTS contexts_new;
DROP TABLE IF EXISTS books_genres_new;
DROP TABLE IF EXISTS books_authors_new;
DROP TABLE IF EXISTS genres_new;
DROP TABLE IF EXISTS books_new;
DROP TABLE IF EXISTS authors_new;

-- Creates the necessary tables to be used by autogenerated inserts.
CREATE TABLE authors_new (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL COMMENT 'Autora vārds mūsdienu rakstībā',
  PRIMARY KEY (id),
  UNIQUE (name)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_latvian_ci COMMENT 'Autoru un līdzautoru metadati';

CREATE TABLE genres_new (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL COMMENT 'Žanra vai apakšžanra nosaukums',
  subgenre bool NOT NULL COMMENT 'Vai šis ir apakšžanrs?',
  PRIMARY KEY (id),
  UNIQUE (name)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_latvian_ci COMMENT 'Avotu žanri un apakšžanri';

CREATE TABLE books_new (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  full_source varchar(50) NOT NULL COMMENT 'Pilnais cilvēklasāmais avota identifikators, kas tiek lietots visos SENIE rīkos, formā kolekcija/grāmata, unikāls',
  collection_code varchar(40) COMMENT 'Kolekcijas cilvēklasāmais identifikators, ja avots ietilpst kolekcijā, tukšs citādi',
  item_code varchar(40) COMMENT 'Avota cilvēklasāmais identifikators kolekcijā, tukšs, ja šis ir kolekcijas kopējo metadatu ieraksts',
  name varchar(100) NOT NULL COMMENT 'Avota publiski rādāmais nosaukums vai iesauka',
  year1 smallint unsigned NOT NULL COMMENT 'Avota radīšanas sākuma gads',
  year2 smallint unsigned NOT NULL COMMENT 'Avota radīšanas beigu gads',
  pub_century tinyint unsigned NOT NULL COMMENT 'Avota gadsimts',
  index_type enum('GNP', 'GLR', 'LR', 'P') COMMENT 'Avota indeksēšanas tips (norāde, kas ir mazākā adresējamā vienība avotā), tukšs kolekcijām',
  manuscript boolean COMMENT 'Vai šis avots ir manuskripts?',
  order_in_collection tinyint unsigned DEFAULT 0 COMMENT 'Avota kārtas numurs kolekcijā, ja avots ir kolekcijas daļa.',
  
  PRIMARY KEY (id),
  UNIQUE (full_source),
  INDEX (full_source)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_latvian_ci COMMENT 'Avota metadati';

CREATE TABLE books_genres_new (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  source varchar(50) NOT NULL COMMENT 'Norāde uz avotu',
  genre_id smallint unsigned NOT NULL COMMENT 'Norāde uz avota žanru',

  PRIMARY KEY (id),
  FOREIGN KEY (source) REFERENCES books_new(full_source),
  FOREIGN KEY (genre_id) REFERENCES genres_new(id)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_latvian_ci COMMENT 'Avota sasaiste ar žanriem';

CREATE TABLE books_authors_new (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  source varchar(50) NOT NULL COMMENT 'Norāde uz avotu',
  author_id smallint unsigned NOT NULL COMMENT 'Norāde uz avota autoru',
  top_author boolean COMMENT 'Vai šis ir galvenais autors, kas norādīts avota sākumā (true) vai līdzautors, kas norādīts avota vidū (false)?',

  PRIMARY KEY (id),
  FOREIGN KEY (source) REFERENCES books_new(full_source),
  FOREIGN KEY (author_id) REFERENCES authors_new(id)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_latvian_ci COMMENT 'Avota sasaiste ar autoriem';


CREATE TABLE contexts_new (
  id int unsigned NOT NULL AUTO_INCREMENT,
  source varchar(50) NOT NULL COMMENT 'Avots, nu kura nāk šī teksta vienība',
  adress varchar(100) COMMENT 'Teksta vienības cilvēklasāmā adrese, P un GNP gadījumā var sakrist vairākām rindām, ir tukša dekoratīvajām bezteksta rindām',
  page varchar(40) COMMENT 'Lappuses numurs, kurā atrodas šī teksta vienība',
  html_line_order smallint unsigned NOT NULL COMMENT 'HTML vienības kārtas numurs, lai attēlojot var rindas sakārtot pareizi',
  data_html text NOT NULL COMMENT 'HTML noformēts teksta vienības saturs',
  data_plain text NOT NULL COMMENT 'Tīrs teksta vienības saturs (ar DSL marķējumu, bet bez HTML)',

  PRIMARY KEY (id),
  FOREIGN KEY (source) REFERENCES books_new(full_source),
  INDEX (source),
  INDEX (adress),
  INDEX (page)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_latvian_ci COMMENT 'Avotu tekstuālais saturs, sadalīts rindās';
