package LvSenieTranslit::TranslitTables;
use strict;
use warnings FATAL => 'all';
use utf8;

use Exporter();
our @ISA = qw(Exporter);
our @EXPORT_OK = qw(substTable hasTable encodeString decodeString);

our $ST = {
	'Manc1638_Run' => {
		'ẜwähtz' => 'svēts',
		'Sweed' => 'Zvied',
		'Wehſch' => 'Vējš',
		'W' => 'V',
		'zeetz' => 'ciets',
		'zeet' => 'ciet',
		'ee' => 'ie',
		'Ee' => 'Ie',
		'unna' => 'unā',
		'nn' => 'n',
		'Chr' => 'Kr',
		'tſch' => 'č',
		'aſchu' => 'āšu',
		'daſſch' => 'dažs',
		'ſſch' => 'š',
		'Scha' => 'Ža',
		'Sch' => 'Š',
		'Jaw' => 'Jau',
		'jaw(\b|$)' => 'jau',
		'ſw' => 'sv',
		'w' => 'v',
		'Z' => 'C',
		'ļļ' => 'ļ',
		'dries' => 'drīz',
		'ieds' => 'īdz',
		'ieeſch' => 'īž',
		'ie' => 'ī',
		'Atz' => 'Atc',
		'(\b|^)Patz(\b|$)' => 'Pats',
		'(\b|^)patz(\b|$)' => 'pats',
		'(\b|^)pattz(\b|$)' => 'pats',
		'(\b|^)zitts(\b|$)' => 'cits',
		'tt' => 't',
		'wätzu' => 'vecu',
		'wätz' => 'vecs',
		'Vh' => 'Ū',
		'Vs' => 'Uz',
		'(\b|^)vs' => 'uz',
		'David' => 'Dāvids',
		'v' => 'u',
		'Drieß' => 'Drīz',
		'Sarrß' => 'Zars',
		'Sutt' => 'Zut',
		'Si' => 'Zi',
		'rr' => 'r',
		'ŗŗ' => 'ŗ',
		'ñ' => 'n',
		'ghajam' => 'gājām',
		'gh' => 'g',
		'Gh' => 'G',
		'ckſch' => 'kš',
		'ck' => 'k',
		'mähds' => 'mēdz',
		'äh' => 'ē',
		'Ꞩch' => 'Š',
		'Ꞩ' => 'S',
		'auxtais' => 'augstais',
		'x' => 'ks',
		'nh' => 'n',
		'Nh' => 'N',
		'bahß' => 'bāz',
		'Kahtz' => 'Kāts',
		'Sah' => 'Zā',
		'ah' => 'ā',
		'Ahſch' => 'Āž',
		'Ah' => 'Ā',
		'bb' => 'b',
		'(\b|^)iß' => 'iz',
		'Jß' => 'Iz',
		'Iß' => 'Iz',
		'ß' => 's',
		'ſẜiſch' => 'sīš',
		'ſẜ' => 's',
		'ö' => 'e',
		'uhds' => 'ūdz',
		'buhſ' => 'būs',
		'uh' => 'ū',
		'Soh' => 'Zo',
		'oh' => 'o',
		'Oh' => 'O',
		'dauds' => 'daudz',
		'ſedds' => 'sedz',
		'ẜedds' => 'sedz',
		'ddſch' => 'dž',
		'dſirehß' => 'dzīrēs',
		'dſ' => 'dz',
		'Dſ' => 'Dz',
		'gg' => 'g',
		'ņņ' => 'ņ',
		'näſ' => 'nes',
		'(\b|^)ſä' => 'ze',
		'mäll' => 'mell',
		'Mäll' => 'Mell',
		'ä' => 'e',
		'pehts' => 'pēc',
		'ehtz' => 'ēc',
		'tz' => 'c',
		'eh' => 'ē',
		'Eh' => 'Ē',
		'à' => 'ā',
		'ẜch' => 'še',
		'ẜ' => 's',
		'ings' => 'iņš',
		'ing' => 'iņ',
		'gir' => 'jir',
		'Gir' => 'Jir',
		'gk' => 'ķ',
		'' => '',
		'ih' => 'ī',
		'by' => 'bij',
		'By' => 'Bij',
		'ſi' => 'zi',
		'ſt' => 'st',
		'ſk' => 'sk',
		'ſp' => 'sp',
		'ſm' => 'zm',
		'ſn' => 'zn',
		'ſl' => 'sl',
		'llſch' => 'ļš',
		'allaſch' => 'allaž',
		'all' => 'all',
		'Jll' => 'Il',
		'llu' => 'llu',
		'ſal' => 'sa',
		'll' => 'l',
		'pp' => 'p',
		'py' => 'pi',
		'Py(\b|$)' => 'Pi',
		'th' => 't',
		'Th' => 'T',
		'dd' => 'd',
		'Ney' => 'Nei',
		'ney' => 'nei',
		'ey ' => 'ej',
		'Ey' => 'Ej',
		'nj' => 'ņ',
		'mm' => 'm',
		'm̃  ' => 'm',
		'jemb' => 'jem',
		'Mbt' => 'mt',
		'(\b|^)z' => 'c',
		'kſch' => 'kš',
		'ſchk' => 'šk',
		'aſch' => 'až',
		'diſch' => 'diža',
		'brieſch' => 'brīž',
		'Meeſch' => 'Miež',
		'Meſch' => 'Mež',
		'Muiſch' => 'Muiž',
		'ſchuhſt' => 'žūst',
		'laiſch' => 'laiž',
		'uſchi' => 'uši',
		'ſch' => 'š',
		'Ais' => 'Aiz',
		'Ais(\b|$)' => 'Aiz',
		'(\b|^)ais' => 'aiz',
		'Auſ' => 'Auz',
		'Se' => 'Ze',
		'ſal' => 'sa',
		'ſe' => 'ze',
		'mas' => 'maz',
		'Mas(\b|$)' => 'Maz',
		'Kaj' => 'Kāj',
		'Maj' => 'Māj',
		'maj' => 'māj',
		'tada' => 'tāda',
		'(\b|^)ta/' => 'tā/',
		'(\b|^)ta(\b|$)' => 'tā',
		'(\b|^)Ta(\b|$)' => 'Tā',
		'ay' => 'ai',
		'yi' => 'ji',
		'(\b|^)ja=' => 'jā=',
		'ſ' => 'z',
		'z' => 'c',
		'y' => 'ī',
		'Qu' => 'Kv',
	},
};

sub substTable
{
	my $tableName = shift @_;
	return $ST->{$tableName};
}

sub hasTable
{
	my $tableName = shift @_;
	return exists $ST->{$tableName};
}

sub encodeString
{
	my $string = shift @_;
	$string =~ s/(.)/\N{U+E001}$1\N{U+E002}/g;
	return $string;
}

sub decodeString
{
	my $string = shift @_;
	$string =~ s/[\N{U+E001}\N{U+E002}]//g;
	#$string =~ tr/\x{E001}\x{E002}//g;
	return $string;
}
1;