-- Preparing database for autogenerated INSERTs.

-- Drops the old tables.
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS content_lines;
DROP TABLE IF EXISTS pages;
DROP TABLE IF EXISTS books_genres;
DROP TABLE IF EXISTS books_authors;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;
SET FOREIGN_KEY_CHECKS = 1;

-- Creates the necessary tables to be used by autogenerated inserts.
CREATE TABLE authors (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL COMMENT 'Autora vārds mūsdienu rakstībā',
  PRIMARY KEY (id),
  UNIQUE (name)
) COMMENT 'Autoru un līdzautoru metadati';

CREATE TABLE genres (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL COMMENT 'Žanra vai apakšžanra nosaukums',
  subgenre bool NOT NULL COMMENT 'Vai šis ir apakšžanrs?',
  PRIMARY KEY (id),
  UNIQUE (name)
) COMMENT 'Avotu žanri un apakšžanri';

CREATE TABLE books (
  full_source_code varchar(50) NOT NULL COMMENT 'Pilnais cilvēklasāmais avota identifikators, kas tiek lietots visos SENIE rīkos, formā kolekcija/grāmata, unikāls',
  collection_code varchar(40) COMMENT 'Kolekcijas cilvēklasāmais identifikators, ja avots ietilpst kolekcijā, tukšs citādi',
  item_code varchar(40) COMMENT 'Avota cilvēklasāmais identifikators kolekcijā, tukšs, ja šis ir kolekcijas kopējo metadatu ieraksts',
  name varchar(100) NOT NULL COMMENT 'Avota publiski rādāmais nosaukums vai iesauka',
  year1 smallint unsigned NOT NULL COMMENT 'Avota radīšanas sākuma gads',
  year2 smallint unsigned NOT NULL COMMENT 'Avota radīšanas beigu gads',
  pub_century tinyint unsigned NOT NULL COMMENT 'Avota gadsimts',
  index_type enum('GNP', 'GLR', 'LR', 'P') COMMENT 'Avota indeksēšanas tips (norāde, kas ir mazākā adresējamā vienība avotā), tukšs kolekcijām',
  manuscript boolean COMMENT 'Vai šis avots ir manuskripts?',
  order_in_collection decimal(10,5) unsigned DEFAULT 0 COMMENT 'Avota kārtas numurs kolekcijā, ja avots ir kolekcijas daļa.',
  PRIMARY KEY (full_source_code),
  INDEX (full_source_code),
  INDEX (collection_code),
  INDEX (item_code),
  CONSTRAINT collection_or_item_code_required CHECK (COALESCE(`collection_code`, `item_code`) IS NOT NULL)
) COMMENT 'Avota metadati';

CREATE TABLE books_genres (
  source varchar(50) NOT NULL COMMENT 'Norāde uz avotu',
  genre_id smallint unsigned NOT NULL COMMENT 'Norāde uz avota žanru',
  PRIMARY KEY (source, genre_id),
  FOREIGN KEY (source) REFERENCES books(full_source_code),
  FOREIGN KEY (genre_id) REFERENCES genres(id),
  CONSTRAINT genre_unique_per_source UNIQUE (source, genre_id)
) COMMENT 'Avota sasaiste ar žanriem';

CREATE TABLE books_authors (
  source varchar(50) NOT NULL COMMENT 'Norāde uz avotu',
  author_id smallint unsigned NOT NULL COMMENT 'Norāde uz avota autoru',
  is_cover_author boolean NOT NULL COMMENT 'Vai šis ir galvenais autors (norādīts avotfaila sākumā)?',
  is_fragment_author boolean NOT NULL COMMENT 'Vai šis ir avota fragmenta autors (norādīts avotfaila vidū)?',
  PRIMARY KEY (source, author_id),
  FOREIGN KEY (source) REFERENCES books(full_source_code),
  FOREIGN KEY (author_id) REFERENCES authors(id)
) COMMENT 'Avota sasaiste ar autoriem';

CREATE TABLE pages (
  id int unsigned NOT NULL AUTO_INCREMENT,
  source varchar(50) NOT NULL COMMENT 'Avots, nu kura nāk šī teksta vienība',
  name varchar(40) COMMENT 'Lappuses numurs, kurā atrodas šī teksta vienība, var saturēt burtus un figūriekavas',
  sort_order smallint unsigned NOT NULL COMMENT 'Lappuses kārtas numurs, lai attēlojot var lappuses sakārtot pareizi',
  facsimile_filename TINYTEXT COMMENT 'Lappuses faksimila attēla faila vārds',
  facsimile_checked_on TIMESTAMP COMMENT 'Kad pēdējo reizi ir pārbaudīts, vai lappusei ir faksimils',
  PRIMARY KEY (id),
  FOREIGN KEY (source) REFERENCES books(full_source_code),
  INDEX (source),
  INDEX (name),
  INDEX (sort_order),
  INDEX (facsimile_checked_on),
  CONSTRAINT page_unique_per_source_order_name UNIQUE (source, name, sort_order),
  CONSTRAINT page_sort_order_for_nonnull_pages_only CHECK (`name` IS NOT NULL OR `sort_order` = 0)
) COMMENT 'Avota lappuses';

CREATE TABLE content_lines (
  id int unsigned NOT NULL AUTO_INCREMENT,
  address varchar(100) COMMENT 'Teksta vienības cilvēklasāmā adrese, P un GNP gadījumā var sakrist vairākām rindām, ir tukša bezteksta, lappušu numuru u.tml rindām',
  page_id int unsigned NOT NULL COMMENT 'Norāde, kurā lapā šī teksta vienība atrodas',
  line_sort_order smallint unsigned NOT NULL COMMENT 'Rindiņas kārtas numurs, lai attēlojot var rindas sakārtot pareizi',
  data_html text NOT NULL COMMENT 'HTML noformēts teksta vienības saturs',
  data_plain text NOT NULL COMMENT 'Tīrs teksta vienības saturs (ar DSL marķējumu, bet bez HTML)',
  PRIMARY KEY (id),
  FOREIGN KEY (page_id) REFERENCES pages(id),
  INDEX (address),
  INDEX (line_sort_order)
) COMMENT 'Avotu tekstuālais saturs, sadalīts rindās';

