-- Preparing database for autogenerated INSERTs.

-- Drops the old tables.
DROP TABLE IF EXISTS content;
DROP TABLE IF EXISTS books_genres;
DROP TABLE IF EXISTS books_authors;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;

-- Creates the necessary tables to be used by autogenerated inserts.
CREATE TABLE authors (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL COMMENT 'Autora vārds mūsdienu rakstībā',
  PRIMARY KEY (id),
  UNIQUE (name)
) COMMENT 'Autoru un līdzautoru metadati';

CREATE TABLE genres (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  name varchar(50) NOT NULL COMMENT 'Žanra vai apakšžanra nosaukums',
  subgenre bool NOT NULL COMMENT 'Vai šis ir apakšžanrs?',
  PRIMARY KEY (id),
  UNIQUE (name)
) COMMENT 'Avotu žanri un apakšžanri';

CREATE TABLE books (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  full_source varchar(50) NOT NULL COMMENT 'Pilnais cilvēklasāmais avota identifikators, kas tiek lietots visos SENIE rīkos, formā kolekcija/grāmata, unikāls',
  collection_code varchar(40) COMMENT 'Kolekcijas cilvēklasāmais identifikators, ja avots ietilpst kolekcijā, tukšs citādi',
  item_code varchar(40) COMMENT 'Avota cilvēklasāmais identifikators kolekcijā, tukšs, ja šis ir kolekcijas kopējo metadatu ieraksts',
  name varchar(100) NOT NULL COMMENT 'Avota publiski rādāmais nosaukums vai iesauka',
  year1 smallint unsigned NOT NULL COMMENT 'Avota radīšanas sākuma gads',
  year2 smallint unsigned NOT NULL COMMENT 'Avota radīšanas beigu gads',
  pub_century tinyint unsigned NOT NULL COMMENT 'Avota gadsimts',
  index_type enum('GNP', 'GLR', 'LR', 'P') COMMENT 'Avota indeksēšanas tips (norāde, kas ir mazākā adresējamā vienība avotā), tukšs kolekcijām',
  manuscript boolean COMMENT 'Vai šis avots ir manuskripts?',
  order_in_collection decimal(10,5) unsigned DEFAULT 0 COMMENT 'Avota kārtas numurs kolekcijā, ja avots ir kolekcijas daļa.',
  
  PRIMARY KEY (id),
  UNIQUE (full_source),
  INDEX (full_source),
  INDEX (collection_code),
  INDEX (item_code),
  CONSTRAINT collection_or_item_code_required CHECK (COALESCE(`collection_code`, `item_code`) IS NOT NULL)
) COMMENT 'Avota metadati';

CREATE TABLE books_genres (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  source varchar(50) NOT NULL COMMENT 'Norāde uz avotu',
  genre_id smallint unsigned NOT NULL COMMENT 'Norāde uz avota žanru',

  PRIMARY KEY (id),
  FOREIGN KEY (source) REFERENCES books(full_source),
  FOREIGN KEY (genre_id) REFERENCES genres(id)
) COMMENT 'Avota sasaiste ar žanriem';

CREATE TABLE books_authors (
  id smallint unsigned NOT NULL AUTO_INCREMENT,
  source varchar(50) NOT NULL COMMENT 'Norāde uz avotu',
  author_id smallint unsigned NOT NULL COMMENT 'Norāde uz avota autoru',
  top_author boolean COMMENT 'Vai šis ir galvenais autors, kas norādīts avota sākumā (true) vai līdzautors, kas norādīts avota vidū (false)?',

  PRIMARY KEY (id),
  FOREIGN KEY (source) REFERENCES books(full_source),
  FOREIGN KEY (author_id) REFERENCES authors(id)
) COMMENT 'Avota sasaiste ar autoriem';


CREATE TABLE content (
  id int unsigned NOT NULL AUTO_INCREMENT,
  source varchar(50) NOT NULL COMMENT 'Avots, nu kura nāk šī teksta vienība',
  address varchar(100) COMMENT 'Teksta vienības cilvēklasāmā adrese, P un GNP gadījumā var sakrist vairākām rindām, ir tukša bezteksta, lappušu numuru u.tml rindām',
  page varchar(40) COMMENT 'Lappuses numurs, kurā atrodas šī teksta vienība, var saturēt burtus un figūriekavas',
  page_sort_order smallint unsigned NOT NULL COMMENT 'Lappuses kārtas numurs, lai attēlojot var lappuses sakārtot pareizi',
  line_sort_order smallint unsigned NOT NULL COMMENT 'Rindiņas kārtas numurs, lai attēlojot var rindas sakārtot pareizi',
  data_html text NOT NULL COMMENT 'HTML noformēts teksta vienības saturs',
  data_plain text NOT NULL COMMENT 'Tīrs teksta vienības saturs (ar DSL marķējumu, bet bez HTML)',

  PRIMARY KEY (id),
  FOREIGN KEY (source) REFERENCES books(full_source),
  INDEX (source),
  INDEX (address),
  INDEX (page),
  INDEX (page_sort_order),
  INDEX (line_sort_order),
  CONSTRAINT page_sort_order_for_nonnull_pages_only CHECK (`page` IS NOT NULL OR `page_sort_order` = 0)
) COMMENT 'Avotu tekstuālais saturs, sadalīts rindās';
