CREATE TABLE IF NOT EXISTS senie.authors (
  id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (name)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.books (
  id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source SMALLINT UNSIGNED NOT NULL,
  codificator VARCHAR(15) NOT NULL,
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (codificator)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.categories (
  id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (name)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.coopers (
  author TINYINT UNSIGNED NOT NULL,
  source SMALLINT UNSIGNED NOT NULL,
  UNIQUE KEY (author, source)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.crossforms (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  wordform MEDIUMINT UNSIGNED NOT NULL,
  source SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (wordform, source),
  INDEX (source)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.gnp_contexts (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source SMALLINT UNSIGNED NOT NULL,
  book TINYINT UNSIGNED NOT NULL,
  chapter TINYINT UNSIGNED NOT NULL,
  verse TINYINT UNSIGNED NOT NULL,
  content TEXT NOT NULL,
  plain TEXT,
  PRIMARY KEY (id),
  UNIQUE KEY (source, book, chapter, verse)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.gnp_positions (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  crossform MEDIUMINT UNSIGNED NOT NULL,
  book TINYINT UNSIGNED NOT NULL,
  chapter TINYINT UNSIGNED NOT NULL,
  verse TINYINT UNSIGNED NOT NULL,
  count TINYINT UNSIGNED NOT NULL,
  context MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (crossform, book, chapter, verse)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.lr_contexts (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source SMALLINT UNSIGNED NOT NULL,
  page VARCHAR(15) NOT NULL,
  row TINYINT UNSIGNED NOT NULL,
  content TEXT NOT NULL,
  plain TEXT,
  PRIMARY KEY (id),
  UNIQUE KEY (source, page, row),
  INDEX (page)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.lr_positions (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  crossform MEDIUMINT UNSIGNED NOT NULL,
  page CHAR(15) NOT NULL,
  row TINYINT UNSIGNED NOT NULL,
  count TINYINT UNSIGNED NOT NULL,
  context MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (crossform, page, row)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.p_contexts (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source SMALLINT UNSIGNED NOT NULL,
  verse VARCHAR(15) NOT NULL,
  content TEXT NOT NULL,
  plain TEXT,
  PRIMARY KEY (id),
  UNIQUE KEY (source, verse)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.p_positions (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  crossform MEDIUMINT UNSIGNED NOT NULL,
  verse CHAR(15) NOT NULL,
  count TINYINT UNSIGNED NOT NULL,
  context MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (crossform, verse)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.periods (
  id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (name)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.quotes (
  rnd SMALLINT UNSIGNED NOT NULL,
  text CHAR(200) NOT NULL,
  context CHAR(100) NOT NULL,
  PRIMARY KEY (rnd),
  UNIQUE KEY (text)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.sources (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  codificator VARCHAR(15) NOT NULL,
  name VARCHAR(100) NOT NULL,
  category TINYINT UNSIGNED NOT NULL,
  period TINYINT UNSIGNED NOT NULL,
  facsimile VARCHAR(100) NOT NULL,
  active CHAR(1) NOT NULL DEFAULT '1',
  structure CHAR(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY (codificator)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.tips (
  rnd TINYINT UNSIGNED NOT NULL,
  text CHAR(200) NOT NULL,
  link CHAR(100) NOT NULL,
  PRIMARY KEY (rnd)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.wordforms (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  wordform CHAR(50) NOT NULL,
  PRIMARY KEY (id),
  INDEX (wordform)
)
TYPE=MyISAM;

CREATE TABLE IF NOT EXISTS senie.words (
  rnd SMALLINT UNSIGNED NOT NULL,
  word CHAR(30) NOT NULL,
  sense CHAR(100) NOT NULL,
  context CHAR(100) NOT NULL,
  PRIMARY KEY (rnd),
  UNIQUE KEY (word)
)
TYPE=MyISAM;