-- id, name

INSERT INTO authors VALUES (1, 'Ernsts Gliks');
INSERT INTO authors VALUES (2, 'Georgs Elgers');
INSERT INTO authors VALUES (3, 'Georgs Mancelis');
INSERT INTO authors VALUES (4, 'Jânis Reiters');
INSERT INTO authors VALUES (5, 'Kristofors Fîrekers');
INSERT INTO authors VALUES (6, 'nezinâms');
INSERT INTO authors VALUES (7, 'Heinrihs Âdolfijs');
INSERT INTO authors VALUES (8, 'Nîkolauss Frîdrihs Hespe');
INSERT INTO authors VALUES (9, 'Gerhards Remlings');
INSERT INTO authors VALUES (10, 'Heinrihs Kleinðmits');
INSERT INTO authors VALUES (11, 'Johans Otoniss');
INSERT INTO authors VALUES (12, 'Jakobs Âdolfijs');
INSERT INTO authors VALUES (13, 'Liborijs Depkins');
INSERT INTO authors VALUES (14, 'Francs Johans Cekels');
INSERT INTO authors VALUES (15, 'Nîkolauss Kristofers Hâgemeisters');
INSERT INTO authors VALUES (16, 'Frîdrihs Vilhelms Cekels');
INSERT INTO authors VALUES (17, 'Gothards Frîdrihs Stenders');
INSERT INTO authors VALUES (18, 'Karls Frîdrihs Ðulcs');
INSERT INTO authors VALUES (19, 'Martîns Gotlîbs Agapetuss Loders');
INSERT INTO authors VALUES (20, 'Kristians Râvensbergs');
INSERT INTO authors VALUES (21, 'Georgs Dresels');
INSERT INTO authors VALUES (22, 'Aleksandrs Johans Stenders');
INSERT INTO authors VALUES (23, 'J. J. Lopenove');
INSERT INTO authors VALUES (24, 'O. F. P. Rîls');
INSERT INTO authors VALUES (25, 'Nikolajs Gisberts');
INSERT INTO authors VALUES (26, 'Simons Grûnavs');
INSERT INTO authors VALUES (27, 'Volfgangs Lâcijs');
INSERT INTO authors VALUES (28, 'Hieronîms Megisers');
INSERT INTO authors VALUES (29, 'Bruno');
INSERT INTO authors VALUES (30, 'Johans Hazentçters');
INSERT INTO authors VALUES (31, 'Heinrihs Fûrmans');
INSERT INTO authors VALUES (32, 'Mihaels Vitenburgs');
INSERT INTO authors VALUES (33, 'Johans Bernevics');
INSERT INTO authors VALUES (34, 'Erihs Johans Fotangels');
INSERT INTO authors VALUES (35, 'Johaness Kaspars Merklins');
INSERT INTO authors VALUES (36, 'Johans Birgers');
INSERT INTO authors VALUES (37, 'Melhiors Foss');
INSERT INTO authors VALUES (38, 'Andreass Baumans');
INSERT INTO authors VALUES (39, 'Andrç Tevç');
