INSERT INTO books (source, codificator, name) VALUES (3, 'Mt', 'Tas Ewangeliums No Úwehta Matteuúa usrak§tihts');
INSERT INTO books (source, codificator, name) VALUES (3, 'Mk', 'Tas Ewangeljums No Úwehta Markusúa usrak§tihts');
INSERT INTO books (source, codificator, name) VALUES (3, 'Lk', 'Tas Ewangeljums No Úwehta Luhkaúa usrak§tihts');
INSERT INTO books (source, codificator, name) VALUES (3, 'Jn', 'Tas Ewangeljums No Úwehta Jahòa uhsrak§tihts');
INSERT INTO books (source, codificator, name) VALUES (3, 'Apd', 'Tee Darbi To Úwehtu Apu§tuïu');
INSERT INTO books (source, codificator, name) VALUES (3, 'Rm', 'Pahwila ta Apu§tuïa Grahmata us teem Reemeºeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, '1Kor', 'Pahwila ta Apu§tuïa pirma Grahmata uhs teem Korinteºeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, '2Kor', 'Pahwila ta Apu§tuïa ohtra Grahmata uhs teem Korinteºeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, 'Gal', 'Pahwila ta Apu§tuïa Grahmata uhs teem Galateºeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, 'Ef', 'Pahwila ta Apu§tuïa Grahmata uhs teem Ewezeºeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, 'Fil', 'Pahwila ta Apu§tuïa Grahmata uhs teem Wilippeºeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, 'Kol', 'Pahwila ta Apu§tuïa Grahmata uhs teem Koloúúeºeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, '1Tes', 'Pahwila ta Apu§tuïa pirma Grahmata uhs teem Teúúalonikeºeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, '2Tes', 'Pahwila ta Apu§tuïa ohtra Grahmata uhs teem Teúúalonikeºeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, '1Tim', 'Pahwila ta Apu§tuïa pirma Grahmata uhs Timmoteju rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, '2Tim', 'Pahwila ta Apu§tuïa ohtra Grahmata uhs Timoteju rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, 'Tit', 'Pahwila ta Apu§tuïa Grahmata uhs Titu rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, 'Flm', 'Pahwila ta Apu§tuïa Grahmata uhs Wilemonu rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, '1P', 'Pehteºa ta Apu§tuïa pirma Grahmata uhs wiúúeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, '2P', 'Pehteºa ta Apu§tuïa ohtra Grahmata uhs wiúúeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, '1J', 'Jahòa ta Apu§tuïa pirma Grahmata uhs wiúúeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, '2J', 'Jahòa ta Apu§tuïa ohtra Grahmata uhs wiúúeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, '3J', 'Jahòa ta Apu§tuïa treúcha Grahmata');
INSERT INTO books (source, codificator, name) VALUES (3, 'Ebr', 'Grahmata uhs teem Ebre`e`ºeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, 'Jk', 'Jehkaba ta Apu§tuïa Grahmata uhs wiúúeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, 'Jud', 'Juhda ta Apu§tuïa Grahmata uhs wiúúeem rak§tita');
INSERT INTO books (source, codificator, name) VALUES (3, 'Atk', 'Ta Úwehta Deewa=Mahzitaja Jahòa Parahdiúchanas=Grahmata');