-- id, source, codificator, name

INSERT INTO books VALUES (1, 3, 'Mt', 'Tas Ewangeliums No Úwehta Matteuúa usrak§tihts');
INSERT INTO books VALUES (2, 3, 'Mk', 'Tas Ewangeljums No Úwehta Markusúa usrak§tihts');
INSERT INTO books VALUES (3, 3, 'Lk', 'Tas Ewangeljums No Úwehta Luhkaúa usrak§tihts');
INSERT INTO books VALUES (4, 3, 'Jn', 'Tas Ewangeljums No Úwehta Jahòa uhsrak§tihts');
INSERT INTO books VALUES (5, 3, 'Apd', 'Tee Darbi To Úwehtu Apu§tuïu');
INSERT INTO books VALUES (6, 3, 'Rm', 'Pahwila ta Apu§tuïa Grahmata us teem Reemeºeem rak§tita');
INSERT INTO books VALUES (7, 3, '1Kor', 'Pahwila ta Apu§tuïa pirma Grahmata uhs teem Korinteºeem rak§tita');
INSERT INTO books VALUES (8, 3, '2Kor', 'Pahwila ta Apu§tuïa ohtra Grahmata uhs teem Korinteºeem rak§tita');
INSERT INTO books VALUES (9, 3, 'Gal', 'Pahwila ta Apu§tuïa Grahmata uhs teem Galateºeem rak§tita');
INSERT INTO books VALUES (10, 3, 'Ef', 'Pahwila ta Apu§tuïa Grahmata uhs teem Ewezeºeem rak§tita');
INSERT INTO books VALUES (11, 3, 'Fil', 'Pahwila ta Apu§tuïa Grahmata uhs teem Wilippeºeem rak§tita');
INSERT INTO books VALUES (12, 3, 'Kol', 'Pahwila ta Apu§tuïa Grahmata uhs teem Koloúúeºeem rak§tita');
INSERT INTO books VALUES (13, 3, '1Tes', 'Pahwila ta Apu§tuïa pirma Grahmata uhs teem Teúúalonikeºeem rak§tita');
INSERT INTO books VALUES (14, 3, '2Tes', 'Pahwila ta Apu§tuïa ohtra Grahmata uhs teem Teúúalonikeºeem rak§tita');
INSERT INTO books VALUES (15, 3, '1Tim', 'Pahwila ta Apu§tuïa pirma Grahmata uhs Timmoteju rak§tita');
INSERT INTO books VALUES (16, 3, '2Tim', 'Pahwila ta Apu§tuïa ohtra Grahmata uhs Timoteju rak§tita');
INSERT INTO books VALUES (17, 3, 'Tit', 'Pahwila ta Apu§tuïa Grahmata uhs Titu rak§tita');
INSERT INTO books VALUES (18, 3, 'Flm', 'Pahwila ta Apu§tuïa Grahmata uhs Wilemonu rak§tita');
INSERT INTO books VALUES (19, 3, '1P', 'Pehteºa ta Apu§tuïa pirma Grahmata uhs wiúúeem rak§tita');
INSERT INTO books VALUES (20, 3, '2P', 'Pehteºa ta Apu§tuïa ohtra Grahmata uhs wiúúeem rak§tita');
INSERT INTO books VALUES (21, 3, '1J', 'Jahòa ta Apu§tuïa pirma Grahmata uhs wiúúeem rak§tita');
INSERT INTO books VALUES (22, 3, '2J', 'Jahòa ta Apu§tuïa ohtra Grahmata uhs wiúúeem rak§tita');
INSERT INTO books VALUES (23, 3, '3J', 'Jahòa ta Apu§tuïa treúcha Grahmata');
INSERT INTO books VALUES (24, 3, 'Ebr', 'Grahmata uhs teem Ebre`e`ºeem rak§tita');
INSERT INTO books VALUES (25, 3, 'Jk', 'Jehkaba ta Apu§tuïa Grahmata uhs wiúúeem rak§tita');
INSERT INTO books VALUES (26, 3, 'Jud', 'Juhda ta Apu§tuïa Grahmata uhs wiúúeem rak§tita');
INSERT INTO books VALUES (27, 3, 'Atk', 'Ta Úwehta Deewa=Mahzitaja Jahòa Parahdiúchanas=Grahmata');

INSERT INTO books VALUES (28, 17, '1Moz', 'Ta Pirma Moh§us Grahmata');
INSERT INTO books VALUES (29, 17, '2Moz', 'Ta Ohtra Moh§us Grahmata');
INSERT INTO books VALUES (30, 17, '3Moz', 'Ta Treúcha Moh§us Grahmata');
INSERT INTO books VALUES (31, 17, '4Moz', 'Ta zettorta Moh§us Grahmata');
INSERT INTO books VALUES (32, 17, '5Moz', 'Ta peekta Moh§us Grahmata');
INSERT INTO books VALUES (33, 17, 'Joz', 'Ta Jo§uu#s Grahmata');
INSERT INTO books VALUES (34, 17, 'Sog', 'Ta Úohìu Grahmata');
INSERT INTO books VALUES (35, 17, 'Rut', 'Ruttes Grahmata');
INSERT INTO books VALUES (36, 17, '1Sam', 'Ta pirma Samueïa Grahmata');
INSERT INTO books VALUES (37, 17, '2Sam', 'Ta ohtra Samueïa Grahmata');
INSERT INTO books VALUES (38, 17, '1Ken', 'Ta pirma Grahmata no teem Íehniòeem');
INSERT INTO books VALUES (39, 17, '2Ken', 'Ta ohtra Grahmata no teem Íehniòeem');
