-- id, codificator, name, category, period, facsimile, active, structure

INSERT INTO sources VALUES (1, 'Ench1615', 'Enchiridion', 1, 1, '', '1', 'LR');
INSERT INTO sources VALUES (2, 'Elg1621_GCG', 'Geistliche Catholiche Gesänge', 1, 1, 'http://korpuss.lv/senie/faksimili/17gs/Elg1621_GCG/', '1', 'LR');
INSERT INTO sources VALUES (3, 'JT1685', 'Tas Jauns Testaments', 1, 1, '', '1', 'GNP');
INSERT INTO sources VALUES (4, 'Manc1654_LP1', 'Lang=gewünschte Lettische Postill I', 1, 1, '', '1', 'LR');
INSERT INTO sources VALUES (5, 'Manc1654_LP2', 'Lang=gewünschte Lettische Postill II', 1, 1, '', '1', 'LR');
INSERT INTO sources VALUES (6, 'Manc1654_LP3', 'Lettische Lang=gewünschte Postill III', 1, 1, 'http://korpuss.lv/senie/faksimili/17gs/Manc1654_LP3/', '1', 'LR');
INSERT INTO sources VALUES (7, 'Reit1675_OD', 'Oratio Dominica XL Linguarum', 1, 1, '', '1', 'LR');
INSERT INTO sources VALUES (8, 'Reit1675_UeP', 'Eine Übersetungsprobe', 1, 1, '', '1', 'LR');
INSERT INTO sources VALUES (9, 'Manc1637_Sal', 'Die Sprüche Salomonis', 1, 1, 'http://korpuss.lv/senie/faksimili/17gs/Manc1637_Sal/', '1', 'LR');
INSERT INTO sources VALUES (10, 'SKL1696_KB', 'Sawadi Karra=Teesas Likkumi', 2, 1, '', '1', 'P');
INSERT INTO sources VALUES (11, 'Eid1701_KB', 'Eid der Treue vor die Lettische Artillerie=Bediente', 2, 2, '', '1', 'P');
INSERT INTO sources VALUES (12, 'SL1684', 'Sohdu=Likkums prett to Behrno=Muschinaschanu', 2, 1, '', '1', 'LR');
INSERT INTO sources VALUES (13, 'SKL1696_RA', 'Sawadi Karra=Teesas Likkumi', 2, 1, '', '1', 'P');
INSERT INTO sources VALUES (14, 'Eid1701_RA', 'Eid der Treue vor die Lettische Artillerie=Bediente', 2, 2, '', '1', 'P');
INSERT INTO sources VALUES (15, 'EvEp1615', 'Euangelia vnd Episteln', 1, 1, 'http://korpuss.lv/senie/faksimili/17gs/EvEp1615/', '1', 'LR');
INSERT INTO sources VALUES (16, 'Ps1615', 'Psalmen vnd geistliche Lieder', 1, 1, '', '1', 'LR');
INSERT INTO sources VALUES (17, 'VD1689_94', 'Ta Swehta Grahmata', 1, 1, '', '1', 'GNP');
INSERT INTO sources VALUES (18, 'Manc1631_Syr', 'Das Haus=, Zucht= vnd Lehrbuch Jesu Syrachs', 1, 1, 'http://korpuss.lv/senie/faksimili/17gs/Manc1631_Syr/', '1', 'LR');
INSERT INTO sources VALUES (19, 'Manc1631_LVM', 'Lettisch Vade mecum', 1, 1, 'http://korpuss.lv/senie/faksimili/17gs/Manc1631_LVM/', '1', 'LR');
INSERT INTO sources VALUES (20, 'Manc1631_LGL', 'Lettische geistliche Lieder vnd Psalmen', 1, 1, 'http://korpuss.lv/senie/faksimili/17gs/Manc1631_LGL/', '1', 'LR');
INSERT INTO sources VALUES (21, 'Manc1631_Cat', 'Der kleine Catechismus', 1, 1, 'http://korpuss.lv/senie/faksimili/17gs/Manc1631_Cat/', '1', 'LR');
INSERT INTO sources VALUES (22, 'LGL1685_K1', 'Lettische geistliche Lieder vnd Collecten', 1, 1, '', '1', 'LR');
INSERT INTO sources VALUES (23, 'LGL1685_V5', 'Lettische geistliche Lieder vnd Collecten', 1, 1, '', '1', 'LR');
INSERT INTO sources VALUES (24, 'VT1689_Prav', 'Tee Praweeschi wissi Latwiski', 1, 1, '', '0', 'LR');
INSERT INTO sources VALUES (25, 'VT1692_Ap', 'Apocrypha', 1, 1, '', '0', 'LR');
INSERT INTO sources VALUES (26, 'Elg1640_EvEp', 'Evangelia et Epistolae', 1, 1, '', '0', 'LR');
INSERT INTO sources VALUES (27, 'EvTA1753', 'Evangelia toto anno', 1, 2, '', '1', 'LR');
INSERT INTO sources VALUES (28, 'Ench1586', 'Enchiridion', 1, 3, 'http://korpuss.lv/senie/faksimili/16gs/Ench1586/', '1', 'LR');
INSERT INTO sources VALUES (29, 'UP1587', 'Vndeudsche Psalmen', 1, 3, 'http://korpuss.lv/senie/faksimili/16gs/UP1587/', '1', 'LR');
INSERT INTO sources VALUES (30, 'EvEp1587', 'Euangelia vnd Epi§teln', 1, 3, 'http://korpuss.lv/senie/faksimili/16gs/EvEp1587/', '1', 'LR');
INSERT INTO sources VALUES (31, 'Fuer1650_70_1ms', 'Lettisches und Teutsches Wörterbuch', 3, 1, '', '1', 'LR');
INSERT INTO sources VALUES (32, 'Fuer1650_70_2ms', 'Lettisches und Teutsches Wörterbuch', 3, 1, '', '1', 'LR');
INSERT INTO sources VALUES (33, 'Depk1704_Vortr', 'Vortrab', 3, 2, '', '1', 'LR');
INSERT INTO sources VALUES (34, 'Depk1704_LW1ms', 'Lettisches Wörterbuch', 3, 2, '', '0', 'LR');
INSERT INTO sources VALUES (35, 'SL1789', 'Skolas likumi', 2, 2, 'http://korpuss.lv/senie/faksimili/18gs/SL1789/', '1', 'LR');
INSERT INTO sources VALUES (36, 'CekFJ1790_KD', 'Kartupeļu dārzs', 2, 2, 'http://korpuss.lv/senie/faksimili/18gs/CekFJ1790_KD/', '1', 'LR');
INSERT INTO sources VALUES (37, 'Hag1790_IM', 'Īsa mācība priekš latviešiem', 2, 2, 'http://korpuss.lv/senie/faksimili/18gs/Hag1790_IM/', '1', 'LR');
INSERT INTO sources VALUES (38, 'CekFV1796_NL', 'Neapskāpjami likumi', 2, 2, 'http://korpuss.lv/senie/faksimili/18gs/CekFV1796_NL/', '1', 'LR');
INSERT INTO sources VALUES (39, 'StendGF1789_SL', 'Ziņģu lustes', 2, 2, 'http://korpuss.lv/senie/faksimili/18gs/StendGF1789_SL/', '1', 'LR');
INSERT INTO sources VALUES (40, 'Sulc1764_ARMST', 'Aizkraukles muižas un Rīmaņmuižas likumi dzimtļaudīm', 2, 2, 'http://korpuss.lv/senie/faksimili/18gs/Sulc1764_ARMST/', '1', 'LR');
INSERT INTO sources VALUES (41, 'Lod1775_SEAPP', 'Sprediķis pie iesvētīšanas', 2, 2, 'http://korpuss.lv/senie/faksimili/18gs/Lod1775_SEAPP/', '1', 'LR');
INSERT INTO sources VALUES (42, 'MD1788', 'Mīļi Draugi!', 2, 2, 'http://korpuss.lv/senie/faksimili/18gs/MD1788/', '1', 'LR');
INSERT INTO sources VALUES (43, 'TII1790', 'Tā īsa izstāstīšana', 2, 2, 'http://korpuss.lv/senie/faksimili/18gs/TII1790/', '1', 'LR');
INSERT INTO sources VALUES (44, 'Lod1778_WTMD', 'Vārdi tās mūžīgas dzīvošanas', 2, 2, 'http://korpuss.lv/senie/faksimili/18gs/Lod1778_WTMD/', '1', 'LR');
INSERT INTO sources VALUES (45, 'Rav1767_SD', 'Svētas domas', 2, 2, 'http://korpuss.lv/senie/faksimili/18gs/Rav1767_SD/', '1', 'LR');
INSERT INTO sources VALUES (46, 'Dres1682_SBM', 'Swähta Bährno=Mahziba', 1, 1, 'http://korpuss.lv/senie/faksimili/17gs/Dres1682_SBM/', '1', 'LR');
INSERT INTO sources VALUES (47, 'StendAJ1790_LSMP', 'Lu§tesśpehle no Semmneeka kas par Mui§chneeku tappe pahrwehr§ts un weena Paśakka no Drauga Lizzepura', 2, 2, '', '1', 'LR');
INSERT INTO sources VALUES (48, 'CC1585', 'Catechismvs Catholicorum', 1, 3, '', '1', 'LR');
INSERT INTO sources VALUES (49, 'Lop1800_SDLS', 'Sarunāšanas starp diviem latviskiem zemniekiem Bērze un Kalniņ', 2, 4, 'http://korpuss.lv/senie/faksimili/19gs/Lop1800_SDLS/', '1', 'LR');
INSERT INTO sources VALUES (50, 'Manc1638_L', 'Lettus', 3, 1, 'http://korpuss.lv/senie/faksimili/17gs/Manc1638_L/', '1', 'LR');
INSERT INTO sources VALUES (51, 'VLH1685', 'Lettisches Hand=buch', 1, 1, 'http://korpuss.lv/senie/faksimili/17gs/VLH1685/html/', '1', 'LR');
INSERT INTO sources VALUES (52, 'Manc1638_Run', '10 sarunas', 2, 1, 'http://korpuss.lv/senie/faksimili/17gs//Manc1638_Run/', '1', 'LR');
INSERT INTO sources VALUES (53, 'Manc1638_PhL', 'Phraseologia Lettica', 3, 1, 'http://korpuss.lv/senie/faksimili/17gs/Manc1638_PhL/', '1', 'LR');
INSERT INTO sources VALUES (54, 'VLH1685_Syr', 'Das Haus=, Zucht= vnd Lehrbuch Jesus Syrachs..', 1, 1, 'http://korpuss.lv/senie/faksimili/17gs/VLH1685_Syr/', '1', 'LR');
INSERT INTO sources VALUES (55, 'Gis1507_PN', 'Gisberta tēvreize', 1, 3, '', '1', 'LR');
INSERT INTO sources VALUES (56, 'Gr1520_PN', 'Grūnava tēvreize', 1, 3, '', '1', 'LR');
INSERT INTO sources VALUES (57, 'Laz1557_PN', 'Lācija tēvreize', 1, 3, '', '1', 'LR');
INSERT INTO sources VALUES (58, 'Meg1593_PN', 'Megisera tēvreize', 1, 3, '', '1', 'LR');
INSERT INTO sources VALUES (59, 'Br1520_PN', 'Bruno tēvreize', 1, 3, '', '1', 'LR');
INSERT INTO sources VALUES (60, 'Has1550_PN', 'Hazentētera tēvreize', 1, 3, '', '1', 'LR');
INSERT INTO sources VALUES (61, 'VLH1685_Sal', 'Die Sprüche Salomonis', 1, 1, '', '1', 'LR');
INSERT INTO sources VALUES (62, 'LS1625', 'Linaudēju šrāga', 2, 1, '', '1', 'LR');
INSERT INTO sources VALUES (63, 'Zv1681_Liec_1', 'Liecinieku zvērests', 2, 1, '', '1', 'LR');
INSERT INTO sources VALUES (64, 'Zv1681_Liec_2', 'Liecinieku zvērests', 2, 1, '', '1', 'LR');
INSERT INTO sources VALUES (65, 'Zv1681_Kok', 'Nevācu koku šķirotāju zvērests', 2, 1, '', '1', 'LR');
INSERT INTO sources VALUES (66, 'ZP1685', '', 2, 1, '', '1', 'LR');
INSERT INTO sources VALUES (67, 'Witt1696_MMID', '', 2, 1, '', '1', 'LR');
INSERT INTO sources VALUES (68, 'Fuhr1690_LL', '', 2, 1, '', '1', 'LR');
INSERT INTO sources VALUES (69, 'VLH1685_Cat', 'Der kleine Catechi§mus', 1, 1, '', '1', 'LR');
INSERT INTO sources VALUES (70, 'Zv1689_Salsnes', 'Sālsnesēju amata zvērests', 2, 1, '', '1', 'LR');
INSERT INTO sources VALUES (71, 'Zv1638_VAR', 'Ziņu sniedzēja zvērests Vidzemes arklu revīzijā', 2, 1, '', '1', 'LR');
INSERT INTO sources VALUES (72, 'Zv1698_Lig', 'Liģeru amata zvērests', 2, 1, '', '1', 'LR');
INSERT INTO sources VALUES (73, 'Zv1689_Kan', 'Kaņepāju kulstītāju amata zvērests', 2, 1, '', '1', 'LR');
INSERT INTO sources VALUES (74, 'Baum1699_LVV', 'Labbajs wehleśchanas Wahrds', 2, 1, '', '1', 'LR');
INSERT INTO sources VALUES (75, 'Thev1575_PN', 'Tevē tēvreize', 1, 3, '', '1', 'LR');
INSERT INTO sources VALUES (76, 'Witt1702_PAN', 'Ta paneśama Auna=Na§ta apdohmata', 2, 1, '', '1', 'LR');
INSERT INTO sources VALUES (77, 'SLM1648', 'Lotawicae', 2, 1, '', '1', 'LR');
INSERT INTO sources VALUES (78, 'V1771_SZA', 'Sila zemnieka Anša vēstule mācītājam Loderam', 2, 2, '', '1', 'LR');
