INSERT INTO sources (codificator, name, category, period) VALUES ('Ench1615', 'Enchiridion', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('Elg1621_GCG', 'Geistliche Catholiche Gesänge', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('JT1685', 'Tas Jauns Testaments', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('Manc1654_LP1', 'Lang=gewünschte Lettische Postill I', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('Manc1654_LP2', 'Lang=gewünschte Lettische Postill II', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('Manc1654_LP3', 'Lettische Lang=gewünschte Postill III', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('Reit1675_OD', 'Oratio Dominica XL Linguarum', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('Reit1675_UeP', 'Eine Übersetungsprobe', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('Manc1637_Sal', 'Die Sprüche Salomonis', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('SKL1696_KB', 'Sawadi Karra=Teesas Likkumi', 2, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('Eid1701_KB', 'Eid der Treue vor die Lettische Artillerie=Bediente', 2, 2);
INSERT INTO sources (codificator, name, category, period) VALUES ('SL1684', 'Sohdu=Likkums prett to Behrno=Muschinaschanu', 2, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('SKL1696_RA', 'Sawadi Karra=Teesas Likkumi', 2, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('Eid1701_RA', 'Eid der Treue vor die Lettische Artillerie=Bediente', 2, 2);
INSERT INTO sources (codificator, name, category, period) VALUES ('EvEp1615', 'Euangelia vnd Episteln', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('Ps1615', 'Psalmen vnd geistliche Lieder', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('VT1694', 'Ta Swehta Grahmata', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('Manc1631_Syr', 'Das Haus=, Zucht= vnd Lehrbuch Jesu Syrachs', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('Manc1631_LVM', 'Lettisch Vade mecum', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('Manc1631_LGL', 'Lettische geistliche Lieder vnd Psalmen', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('Manc1631_Cat', 'Der kleine Catechismus', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('LGL1685_K1', 'Lettische geistliche Lieder vnd Collecten', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('LGL1685_V5', 'Lettische geistliche Lieder vnd Collecten', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('VT1689_Prav', 'Tee Praweeschi wissi Latwiski', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('VT1692_Ap', 'Apocrypha', 1, 1);
INSERT INTO sources (codificator, name, category, period) VALUES ('Elg1640_EvEp', 'Evangelia et Epistolae', 1, 1);