CREATE TABLE gnp_positions (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  crossform MEDIUMINT UNSIGNED NOT NULL,
  book TINYINT UNSIGNED NOT NULL,
  chapter TINYINT UNSIGNED NOT NULL,
  verse TINYINT UNSIGNED NOT NULL,
  count TINYINT UNSIGNED NOT NULL,
  context MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (crossform, book, chapter, verse)
);