CREATE TABLE lr_positions (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  crossform MEDIUMINT UNSIGNED NOT NULL,
  page CHAR(15) NOT NULL,
  row TINYINT UNSIGNED NOT NULL,
  count TINYINT UNSIGNED NOT NULL,
  context MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (crossform, page, row)
);