CREATE TABLE gnp_contexts (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source SMALLINT UNSIGNED NOT NULL,
  book TINYINT UNSIGNED NOT NULL,
  chapter TINYINT UNSIGNED NOT NULL,
  verse TINYINT UNSIGNED NOT NULL,
  content TEXT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (source, book, chapter, verse)
);