CREATE TABLE p_positions (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  crossform MEDIUMINT UNSIGNED NOT NULL,
  verse CHAR(15) NOT NULL,  
  count TINYINT UNSIGNED NOT NULL,
  context MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (crossform, verse)
);