CREATE TABLE crossforms (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  wordform MEDIUMINT UNSIGNED NOT NULL,
  source SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (wordform, source)
);