package LvSenie::Translit::SimpleTranslitTables;
use strict;
use warnings;
use utf8;

use Exporter();
our @ISA = qw(Exporter);
our @EXPORT_OK = qw(substTable hasTable TABLES);

# Human readable substitution tables.
our $TABLES_SINGLES = {
	'Br1520_PN'   => [ ### IR OK.
		[ '^Tew', 'Tēv', ],
		[ '\b{wb}muſe\b{wb}', 'mūse', ],
		[ '\b{wb}muſs', 'mūs', ],
		[ '\b{wb}Muſse\b{wb}', 'Mūse', ],
		[ '\b{wb}excã\b{wb}', 'iekšan', ],
		[ '\b{wb}eck', 'iek', ],
		[ 'ſch', 'š', ],
		[ 'bb', 'b', ],
		[ 'ſiſs', 'sīs', 1 ],
		[ '\b{wb}Swetytz\b{wb}', 'Svētīts', ],
		[ 'ouw', 'av', ],
		[ '\b{wb}waardt', 'vārds', ],
		[ '\b{wb}Ena', 'Ienā', ],
		[ 'ck', 'k', ],
		[ '\b{wb}wallſtibſs', 'valstībs', ],
		[ 'atz\b{wb}', 'āts', ],
		[ '\b{wb}bus\b{wb}', 'būs', ],
		[ '\b{wb}ka\b{wb}', 'kā', ],
		[ 'ss', 's', ],
		[ '\b{wb}Ta\b{wb}', 'Tā', ],
		[ '\b{wb}arriſ', 'arīdz', ],
		[ '\b{wb}wurſ', 'virs', ],
		[ '\b{wb}ſemm', 'zem', ],
		[ '\b{wb}deniſ', 'dieni', ],
		[ 'yſe\b{wb}', 'ize', ],
		[ '\b{wb}duth\b{wb}', 'dot', ],
		[ 'deẽ', 'dien', ],
		[ 'mm', 'm', ],
		[ '\b{wb}gre', 'grē', ],
		[ '\b{wb}mes\b{wb}', 'mēs', ],
		[ 'rr', 'r', ],
		[ 'adu', 'ādnie', ],
		[ 'ekw', 'iev', ],
		[ 'dſ', 'dz', ],
		[ '\b{wb}ļou', 'ļau', ],
		[ '\b{wb}AEth\s*peſti', 'Atpesti', ],
		[ '\b{wb}wyſ', 'vis', ],
	],
	'Ench1586' => [
		[ '\b{wb}Amen\b{wb}', 'Āmen ', ],
		[ '\b{wb}Jeſ', 'Jēz', ],
		[ '\b{wb}IESVM\b{wb}', 'Jēzum', ],
		[ '\b{wb}Chriſ', 'Kris', ],
		[ '\b{wb}CHRISTVM\b{wb}', 'Kristum', ],
		[ 'kunx\b{wb}', 'kungs', ],
		[ 'zour\b{wb}', 'aur', ],
		[ '\b{wb}gir\b{wb}', '\b{wb}jir\b{wb}', ],
		[ '\b{wb}thew', 'tēv', ],
		[ '\b{wb}ſzouw', 'sav', ],
		[ '\b{wb}thoew', 'tav', ],
		[ '\b{wb}thouwa\b{wb}', 'tava', ],
		[ '\b{wb}ſouw', 'sav', ],
		[ '\b{wb}ßöw\b{wb}', 'sev', ],
		[ '\b{wb}ßouw', 'sav', ],
		[ 'ouw', 'av', ],
		[ '\b{wb}ßoew\b{wb}', 'sev', ],
		[ '\b{wb}peßatcy', 'piesacī', ],
		[ '\b{wb}peß', 'pies', ],
		[ '\b{wb}beß\b{wb}', 'bez', ],
		[ '\b{wb}meßi', 'miesī', ],
		[ '\b{wb}meß', 'mies', ],
		[ '\b{wb}treß', 'trēs', ],
		[ 'teß', 'ties', ],
		[ '\b{wb}eßack', 'iesāk', ],
		[ '\b{wb}ßack', 'sak', ],
		[ '\b{wb}eßi', 'iezīm', ],
		[ '\b{wb}adßiſ', 'atzīs', ],
		[ '\b{wb}adßyth\b{wb}', 'atzīt', ],
		[ '\b{wb}mußyx\b{wb}', 'mūžīgs', ],
		[ '\b{wb}mußi', 'mūžī', ],
		[ '\b{wb}muß', 'mūs', ],
		[ 'ßyx\b{wb}', 'sīgs', ],
		[ '\b{wb}ßaſſetz\b{wb}', 'sasiets', ],
		[ '\b{wb}wueßaſ', 'visas', ],
		[ '\b{wb}wueß', 'vis', ],
		[ '\b{wb}wuerß', 'virs', ],
		[ 'owß', 'aus', ],
		[ '\b{wb}ßay', 'sai', ],
		[ '\b{wb}Jß', 'Iz', ],
		[ '\b{wb}ßouſe\b{wb}', 'sause', ],
		[ '\b{wb}ßouße\b{wb}', 'sause', ],
		[ 'ouß', 'aus', ],
		[ 'Gayß', 'Gais', ],
		[ '\b{wb}allaß', 'a%až', ],
		[ '\b{wb}aßle', 'aizslē', ],
		[ '\b{wb}eßhe\b{wb}', 'ese', ],
		[ '\b{wb}ßheele\b{wb}', 'žēle', ],
		[ '\b{wb}ßelyx\b{wb}', 'žēlīgs', ],
		[ '\b{wb}ßeelyx\b{wb}', 'žēlīgs', ],
		[ '\b{wb}ßeeli', 'žēlī', ],
		[ '\b{wb}ßeel', 'žēl', ],
		[ '\b{wb}ßeli', 'žēlī', ],
		[ '\b{wb}ßeer\b{wb}', 'dzer', ],
		[ '\b{wb}ßinn', 'zin', ],
		[ '\b{wb}ßin\b{wb}', 'zin', ],
		[ 'ßeetc', 'zied', ],
		[ 'ßeczy', 'ziedzī', ],
		[ '\b{wb}ßedczi', 'ziedzī', ],
		[ '\b{wb}ßeryo\b{wb}', 'dzeŗo', ],
		[ '\b{wb}ßwer', 'zvēr', ],
		[ 'ßli', 'slī', ],
		[ 'ßly', 'slī', ],
		[ '\b{wb}ßutys\b{wb}', 'sūtījs', ],
		[ '\b{wb}ßue', 'zi', ],
		[ '\b{wb}ßuudcz', 'sūdz', ],
		[ '\b{wb}tryße', 'trīsē', ],
		[ 'ß', 's', ],
		[ '\b{wb}daſſch', 'daž', ],
		[ '\b{wb}diſſch', 'diž', ],
		[ '\b{wb}Gaſpaſſche\b{wb}', 'Gaspaže', ],
		[ 'ſſuſtcz\b{wb}', 'zusts', ],
		[ 'ſſuſſch', 'zuš', ],
		[ '\b{wb}jſledtcz\b{wb}', 'izliets', ],
		[ '\b{wb}jſledtz\b{wb}', 'izliets', ],
		[ '\b{wb}Jſleys\b{wb}', 'Izlējis', ],
		[ '\b{wb}Jſſaby', 'Izsabij', ],
		[ '\b{wb}Jſrael', 'Izraēl', ],
		[ '\b{wb}iſleys\b{wb}', 'izlējis', ],
		[ 'ſſch', 'š', ],
		[ '\b{wb}eſſhe\b{wb}', 'ese', ],
		[ '\b{wb}wueſſ', 'vis', ],
		[ '\b{wb}wüſſ', 'vis', ],
		[ '\b{wb}muſſi', 'mūžī', ],
		[ '\b{wb}muſſ', 'mūs', ],
		[ 'ſſ', 's', ],
		[ '\b{wb}muſzi', 'mūžī', ],
		[ '\b{wb}muſz', 'mūs', ],
		[ '\b{wb}peſz', 'pies', ],
		[ '\b{wb}meſz', 'mies', ],
		[ 'teſzi', 'tiesī', ],
		[ '\b{wb}ſzyſtz\b{wb}', 'sists', ],
		[ '\b{wb}ayſzeth\b{wb}', 'aizsiet', ],
		[ '\b{wb}adſzith\b{wb}', 'atzīt', ],
		[ 'ſzuſte\b{wb}', 'zuste', ],
		[ 'ſz', 's', ],
		[ 'maſga', 'mazgā', ],
		[ '\b{wb}Baſni', 'Baznī', ],
		[ '\b{wb}peſoutcz', 'piesauc', ],
		[ '\b{wb}peſpeſche\b{wb}', 'piespieže', ],
		[ '\b{wb}ſpeſch', 'spiež', ],
		[ '\b{wb}Meſa\b{wb}', 'Miesa', ],
		[ '\b{wb}Meſe\b{wb}', 'Miese', ],
		[ 'tteſe\b{wb}', 'tiese', ],
		[ 'tteſa\b{wb}', 'tiesa', ],
		[ '\b{wb}teſa\b{wb}', 'tiesa', ],
		[ '\b{wb}teſe', 'tiese', ],
		[ 'ttheſe\b{wb}', 'tiese', ],
		[ 'theſe\b{wb}', 'tiese', ],
		[ 'teſi', 'tiesī', ],
		[ 'teſyx\b{wb}', 'tiesīgs', ],
		[ 'heſtz\b{wb}', 'ēsts', ],
		[ '\b{wb}eſtad', 'iestād', ],
		[ '\b{wb}eſtip', 'iesti', ],
		[ '\b{wb}Eſchen', 'Ēše', ],
		[ '\b{wb}eſchen', 'ieše', ],
		[ '\b{wb}eſy', 'iezī', ],
		[ 'louſe\b{wb}', 'lauze', ],
		[ '\b{wb}ſemm', 'zem', ],
		[ '\b{wb}ſir', 'zir', ],
		[ '\b{wb}mayſe\b{wb}', 'maize', ],
		[ '\b{wb}yuuſ', 'jūs', ],
		[ '\b{wb}yuſ', 'jūs', ],
		[ '\b{wb}Cruſtitcz\b{wb}', 'Krustīts', ],
		[ '\b{wb}cruſtytcz\b{wb}', 'krustīts', ],
		[ '\b{wb}Cruſty', 'Krustīj', ],
		[ '\b{wb}Cruſti', 'Krustī', ],
		[ '\b{wb}Chruſty', 'Krustī', ],
		[ '\b{wb}chruſtitcz\b{wb}', 'krustīts', ],
		[ '\b{wb}chruſti', 'krustī', ],
		[ '\b{wb}Chruſ', 'Krus', ],
		[ 'ſkyſtcz\b{wb}', 'šķīsts', ],
		[ 'ſkyſt', 'šķīst', ],
		[ '\b{wb}Vſyem\b{wb}', 'Uzjem', ],
		[ '\b{wb}vſie', 'uzje', ],
		[ '\b{wb}vſ', 'uz', ],
		[ '\b{wb}ayſledtcze\b{wb}', 'aizliedzis', ],
		[ '\b{wb}ayſka', 'aizskā', ],
		[ 'ayſ', 'ais', ],
		[ '\b{wb}aiſ', 'aiz', ],
		[ '\b{wb}abſkay', 'apskai', ],
		[ '\b{wb}aeeſto\b{wb}', 'aizto', ],
		[ '\b{wb}aeſto\b{wb}', 'aizto', ],
		[ '\b{wb}äſto\b{wb}', 'aizto', ],
		[ '\b{wb}Aſtotz\b{wb}', 'astots', ],
		[ '\b{wb}ſan', 'sān', ],
		[ '\b{wb}Dwheſ', 'Dvēs', ],
		[ '\b{wb}peſkaarſ', 'pieskārs', ],
		[ 'ſty', 'stī', ],
		[ 'ſtitay', 'stītāj', ],
		[ '\b{wb}ſweetye\b{wb}', 'svētīje', ],
		[ '\b{wb}ſweetcz\b{wb}', 'svēts', ],
		[ '\b{wb}ſweetz\b{wb}', 'svēts', ],
		[ '\b{wb}ſwetcz\b{wb}', 'svēts', ],
		[ '\b{wb}ſweet', 'svēt', ],
		[ '\b{wb}ſwet', 'svēt', ],
		[ '\b{wb}ſwed', 'svied', ],
		[ '\b{wb}yſte', 'īste', ],
		[ '\b{wb}Skyſti', 'Šķīstī', ],
		[ '\b{wb}Keyſ', 'Keiz', ],
		[ '\b{wb}Muyſche\b{wb}', 'Muiže', ],
		[ 'iſke\b{wb}', 'išķe', ],
		[ '\b{wb}Seweſk', 'Sievešķ', ],
		[ '\b{wb}Sewi', 'Sievi', ],
		[ 'ſkyrtz\b{wb}', 'šķirts', ],
		[ '\b{wb}ſkir', 'šķir', ],
		[ 'eſkan\b{wb}', 'eškan', ],
		[ 'ſmeetz\b{wb}', 'smets', ],
		[ 'ſmetcz\b{wb}', 'smets', ],
		[ '\b{wb}breſmi', 'briesmī', ],
		[ '\b{wb}Sczeſ ', 'Dzies', ],
		[ '\b{wb}ſczeda', 'dziedā', ],
		[ '\b{wb}ſczeryeth', 'dzerī', ],
		[ '\b{wb}ſcze', 'dze', ],
		[ '\b{wb}ſczirdtcz\b{wb}', 'dzirdts', ],
		[ '\b{wb}Seeſtcz', 'Sests', ],
		[ 'mmeeſ', 'mes', ],
		[ 'mmeſch', 'meš', ],
		[ 'mmeſ', 'mes', ],
		[ '\b{wb}tuſ', 'tūks', ],
		[ 'ſtib', 'stībe', ],
		[ '\b{wb}ſtip', 'sti', ],
		[ 'ſtitais\b{wb}', 'stītājs', ],
		[ '\b{wb}peſti', 'pestī', ],
		[ '\b{wb}byaſch', 'bijāš', ],
		[ '\b{wb}Szinnaſch', 'Zināš', ],
		[ 'aſch', 'āš', ],
		[ '\b{wb}pelaiſche\b{wb}', 'pielaiže', ],
		[ 'leiſche\b{wb}', 'lējše', ],
		[ 'iſch', 'īš', ],
		[ '\b{wb}teſcham\b{wb}', 'tiešām', ],
		[ '\b{wb}czeſch', 'cieš', ],
		[ 'dtczeeſch', 'cēš', ],
		[ 'etczeſch', 'cēš', ],
		[ '\b{wb}Egribbeſch', 'Iegribēš', ],
		[ '\b{wb}preſch', 'prieš', ],
		[ '\b{wb}eheſch', 'ēš ', ],
		[ '\b{wb}eehſch', 'ēš ', ],
		[ '\b{wb}ehſch', 'ēš', ],
		[ '\b{wb}peminneſch', 'pieminēš', ],
		[ '\b{wb}waydheſch', 'vaidēš', ],
		[ 'zixteſch', 'īkstēš', ],
		[ '\b{wb}treſch', 'treš', ],
		[ 'eſch', 'ēš', ],
		[ '\b{wb}cziwoſch', 'dzīvoš', ],
		[ '\b{wb}czywoſch', 'dzīvoš', ],
		[ 'ryoſch', 'ŗoš', ],
		[ '\b{wb}buuſch', 'būš', ],
		[ '\b{wb}peluudtczys\b{wb}', 'pielūdzis', ],
		[ '\b{wb}peluuckſch', 'pielūgš', ],
		[ 'luuckſch', 'lūgš', ],
		[ '\b{wb}peluuckt\b{wb}', 'pielūgt', ],
		[ '\b{wb}Sczerſch', 'dzerš', ],
		[ '\b{wb}Sczeerſch', 'dzerš', ],
		[ 'werſche\b{wb}', 'vērš', ],
		[ '\b{wb}Weerſch', 'Vērš', ],
		[ '\b{wb}ſchems\b{wb}', 'šiems', ],
		[ '\b{wb}ſchims\b{wb}', 'šiems', ],
		[ '\b{wb}ſche\b{wb}', 'šie', ],
		[ 'ſch', 'š', ],
		[ 'ſuſtcz\b{wb}', 'zusts', ],
		[ '\b{wb}Seſtz\b{wb}', 'Sests', ],
		[ 'ſthaw', 'stāv', ],
		[ 'ſthay', 'stāj', ],
		[ '\b{wb}greſn', 'grezn', ],
		[ '\b{wb}greſ', 'griez', ],
		[ 'ouſiht\b{wb}', 'ausīt', ],
		[ 'ouſi', 'ausī', ],
		[ 'ouſy', 'ausī', ],
		[ '\b{wb}adſyd\b{wb}', 'atzīt', ],
		[ 'aiſy', 'aisīj', ],
		[ '\b{wb}ſtayga', 'staigā', ],
		[ '\b{wb}ſtrada', 'strādā', ],
		[ '\b{wb}abduſ', 'apdus', ],
		[ '\b{wb}Semmoſ', 'Zemos', ],
		[ '\b{wb}Semm', 'Zem', ],
		[ 'ſthas\b{wb}', 'stās', ],
		[ 'ſkay', 'skai', ],
		[ '\b{wb}Skirſ', 'Šķirs', ],
		[ '\b{wb}ſpidi', 'spīdī', ],
		[ 'ſmyx\b{wb}', 'smīgs', ],
		[ '\b{wb}kraſ', 'krās', ],
		[ '\b{wb}Pyſ', 'Pīs', ],
		[ 'ſ', 's', ],
		[ 'eexkan\b{wb}', 'iekškan', ],
		[ 'exkan\b{wb}', 'iekškan', ],
		[ 'exan\b{wb}', 'iekšan', ],
		[ '\b{wb}auxamczhe', 'augšāmcē', ],
		[ '\b{wb}auxkam\b{wb}', 'augškām', ],
		[ '\b{wb}auxt', 'augst', ],
		[ '\b{wb}Raxtcz\b{wb}', 'raksts', ],
		[ 'czenyx\b{wb}', 'cienīgs', ],
		[ '\b{wb}Szeelyx\b{wb}', 'Žēlīgs', ],
		[ '\b{wb}Zenix\b{wb}', 'Cienīgs', ],
		[ '\b{wb}Czilwhex\b{wb}', 'Cilvēks', ],
		[ '\b{wb}czilwhe', 'cilvē', ],
		[ '\b{wb}elyx', 'ielīks', ],
		[ '\b{wb}raxtytz\b{wb}', 'rakstīts', ],
		[ 'bax\b{wb}', 'ags', ],
		[ 'oux\b{wb}', 'augs', ],
		[ 'ix\b{wb}', 'īgs', ],
		[ 'yx\b{wb}', 'īgs', ],
		[ 'x', 'ks', ],
		[ '\b{wb}Enay', 'Ienai', ],
		[ 'yumm', 'ījum', ],
		[ '\b{wb}yuus\b{wb}', 'jūs', ],
		[ '\b{wb}yu', 'ju', ],
		[ '\b{wb}peklay', 'pieklāj', ],
		[ '\b{wb}Wayge\b{wb}', 'Vaige', ],
		[ '\b{wb}Wayacz', 'Vajadz', ],
		[ '\b{wb}waya', 'vaja', ],
		[ 'aya', 'āja', ],
		[ '\b{wb}cziwoy', 'dzīvoj', ],
		[ 'oy', 'oj', ],
		[ '\b{wb}eyemptcz\b{wb}', 'iejemts', ],
		[ '\b{wb}eyemptz\b{wb}', 'iejemts', ],
		[ '\b{wb}myleys\b{wb}', 'mīleis', ],
		[ '\b{wb}ladeys\b{wb}', 'lādējs', ],
		[ '\b{wb}enydeys\b{wb}', 'ienīdējs', ],
		[ '\b{wb}Meyt', 'Meit', ],
		[ '\b{wb}Ey', 'Ej', ],
		[ 'ey', 'ēj', ],
		[ 'itaye', 'ītāje', ],
		[ 'aye', 'āje', ],
		[ 'sky', 'šķī', ],
		[ 'pye', 'pje', ],
		[ '\b{wb}Wynerye', 'Vīnerijē', ],
		[ '\b{wb}yemptcz\b{wb}', 'jemts', ],
		[ '\b{wb}yemp', 'jem', ],
		[ '\b{wb}ye', 'je', ],
		[ 'ye\b{wb}', 'īje', ],
		[ '\b{wb}py\b{wb}', 'pi', ],
		[ 'py', 'pi', ],
		[ '\b{wb}aysleckt\b{wb}', 'aizliegt', ],
		[ 'ays\b{wb}', 'ājs', ],
		[ 'ayo', 'ājo', ],
		[ 'etay', 'ētāj', ],
		[ 'ay', 'ai', ],
		[ 'uy', 'ui', ],
		[ 'lydtcze', 'līdze', ],
		[ 'llydtcz', 'līdz', ],
		[ '\b{wb}lydtcz\b{wb}', 'līdz', ],
		[ 'lyos', 'ļos', ],
		[ '\b{wb}czeny', 'cienī', ],
		[ '\b{wb}eny', 'ienī', ],
		[ '\b{wb}abgany', 'apgānī', ],
		[ '\b{wb}Sy', 'Zī', ],
		[ 'rya', 'ŗa', ],
		[ 'ryo', 'ŗo', ],
		[ 'tcytcz\b{wb}', 'cīts', ],
		[ 'tcytz\b{wb}', 'cīts', ],
		[ 'tczy', 'cī', ],
		[ 'tcy', 'cī', ],
		[ '\b{wb}by\b{wb}', 'bij', ],
		[ 'tytcz\b{wb}', 'tīts', ],
		[ '\b{wb}Tytcz', 'Tic', ],
		[ 'tyttz\b{wb}', 'tīts', ],
		[ 'tyz', 'tīts', ],
		[ 'you', 'jau', ],
		[ '\b{wb}Doeuwytcz\b{wb}', 'Devīts', ],
		[ '\b{wb}Doeuwytz\b{wb}', 'Devīts', ],
		[ '\b{wb}Sczyrdtcz\b{wb}', 'Sirds', ],
		[ '\b{wb}Szy', 'Si', ],
		[ '\b{wb}trys\b{wb}', 'trīs', ],
		[ 'ys\b{wb}', 'ījs', ],
		[ 'yli', 'īlī', ],
		[ '\b{wb}gaddy', 'gādī', ],
		[ '\b{wb}Enaidy', 'Ienaidī', ],
		[ 'y', 'ī', ],
		[ '\b{wb}wärdtcz\b{wb}', 'vārds', ],
		[ '\b{wb}prätcz\b{wb}', 'prāts', ],
		[ '\b{wb}prätz\b{wb}', 'prāts', ],
		[ 'ä', 'ā', ],
		[ 'öw', 'ev', ],
		[ 'öe', 'ā', ],
		[ '\b{wb}atkö', 'atko', ],
		[ '\b{wb}Kö', 'Kē', ],
		[ 'ös\b{wb}', 'os', ],
		[ 'öu', 'au', ],
		[ 'ö', 'o', ],
		[ '\b{wb}waerdtcz\b{wb}', 'vārds', ],
		[ '\b{wb}waer', 'vār', ],
		[ 'dtczenā', 'cenā', ],
		[ 'dtczis\b{wb}', 'cis', ],
		[ '\b{wb}Jsledtcz\b{wb}', 'Izliets', ],
		[ '\b{wb}ledtcz', 'liec', ],
		[ 'idtcz', 'īdz', ],
		[ '\b{wb}Lodtcz', 'Loc', ],
		[ 'odtcz\b{wb}', 'ds', ],
		[ '\b{wb}ludtcz', 'lūdz', ],
		[ 'eedtcz', 'edz', ],
		[ 'dtcz', 'dz', ],
		[ '\b{wb}Pecktcz\b{wb}', 'Piekts', ],
		[ 'eczimptcz\b{wb}', 'iedzimts', ],
		[ 'utcze\b{wb}', 'udze', ],
		[ 'tczak', 'cāk', ],
		[ 'itczan\b{wb}', 'īdzan', ],
		[ 'weetcz\b{wb}', 'vēts', ],
		[ '\b{wb}ladeetcz\b{wb}', 'lādēts', ],
		[ '\b{wb}praetcz\b{wb}', 'prāts', ],
		[ '\b{wb}Letczi', 'Liecī', ],
		[ '\b{wb}patcz\b{wb}', 'pats', ],
		[ '\b{wb}taatcz\b{wb}', 'tāds', ],
		[ '\b{wb}dhotcz\b{wb}', 'dots', ],
		[ 'batcz\b{wb}', 'bads', ],
		[ 'aatcz\b{wb}', 'āts', ],
		[ '\b{wb}pewiltcz\b{wb}', 'pievilts', ],
		[ '\b{wb}petitczi', 'pieticī', ],
		[ '\b{wb}peti', 'pieti', ],
		[ 'outcz', 'audz', ],
		[ 'uutcz', 'ūdz', ],
		[ 'tcz', 'c', ],
		[ '\b{wb}ethwertz\b{wb}', 'ietverts', ],
		[ '\b{wb}abbhestz\b{wb}', 'apbēsts', ],
		[ '\b{wb}whettz\b{wb}', 'vecs', ],
		[ 'eetz\b{wb}', 'ēc', ],
		[ '\b{wb}Pecktz\b{wb}', 'Piekts', ],
		[ '\b{wb}Peeck', 'Piek', ],
		[ '\b{wb}patz\b{wb}', 'pats', ],
		[ 'dtz\b{wb}', 'dz', ],
		[ 'tz\b{wb}', 'ts', ],
		[ '\b{wb}czeene\b{wb}', 'ciene', ],
		[ '\b{wb}czee', 'ce', ],
		[ 'czeni', 'cienī', ],
		[ '\b{wb}czek', 'ciek', ],
		[ '\b{wb}czetis\b{wb}', 'cietis', ],
		[ '\b{wb}eprecz', 'iepriec', ],
		[ '\b{wb}Lodcze', 'Loce', ],
		[ 'dczes\b{wb}', 'dzes', ],
		[ '\b{wb}Sczer', 'dzer', ],
		[ '\b{wb}auczen', 'audzen', ],
		[ 'cze', 'ce', ],
		[ '\b{wb}pecz', 'piedz', ],
		[ '\b{wb}cziw', 'dzīv', ],
		[ '\b{wb}adczimp', 'atdzim', ],
		[ '\b{wb}Czimp', 'Dzim', ],
		[ 'dczi', 'dzī', ],
		[ 'gczi', 'gdzī', ],
		[ '\b{wb}czir', 'dzir', ],
		[ '\b{wb}czim', 'zīm', ],
		[ '\b{wb}czille\b{wb}', 'dziļe', ],
		[ 'czh', 'c', ],
		[ 'dcz\b{wb}', 'dz', ],
		[ 'cz', 'c', ],
		[ '\b{wb}Emaet', 'Iemā', ],
		[ 'aetc', 'āc', ],
		[ 'tce', 'ce', ],
		[ '\b{wb}prec', 'priec', ],
		[ 'zhell', 'eļ', ],
		[ 'zell', 'eļ', ],
		[ '\b{wb}abbe\b{wb}', 'abe', ],
		[ '\b{wb}abd', 'apd', ],
		[ '\b{wb}abgadā', 'apgādā', ],
		[ '\b{wb}abg', 'apg', ],
		[ '\b{wb}Dew', 'Diev', ],
		[ '\b{wb}daw', 'dāw', ],
		[ '\b{wb}neewe', 'nevie', ],
		[ '\b{wb}Jckwe', 'Ikvie', ],
		[ '\b{wb}wen', 'vien', ],
		[ '\b{wb}Shode', 'Šodie', ],
		[ 'oden\b{wb}', 'šodien', ],
		[ '\b{wb}Sch', 'Š', ],
		[ '\b{wb}peehd', 'pieēd', ],
		[ 'edth\b{wb}', 'iet', ],
		[ 'eh', 'ē', ],
		[ '\b{wb}wet', 'viet', ],
		[ '\b{wb}Szew', 'Siev', ],
		[ '\b{wb}den', 'dien', ],
		[ '\b{wb}ieb\b{wb}', 'jeb', ],
		[ '\b{wb}leth', 'liet', ],
		[ '\b{wb}let', 'liet', ],
		[ '\b{wb}lel', 'liel', ],
		[ '\b{wb}Neene', 'Nenie', ],
		[ '\b{wb}nee', 'ne', ],
		[ 'wheln', 'eln', ],
		[ '\b{wb}Sackt\b{wb}', 'Zagt', ],
		[ '\b{wb}Peke', 'Pieke', ],
		[ '\b{wb}nawe', 'nāve', ],
		[ 'llec', 'lie', ],
		[ 'oes\b{wb}', 'os', ],
		[ 'oeuw', 'ev', ],
		[ 'oew', 'ev', ],
		[ 'tow', 'tav', ],
		[ 'wheleis\b{wb}', 'vēlējs', ],
		[ 'whelk', 'velk', ],
		[ 'whel', 'vēl', ],
		[ '\b{wb}weel', 'vel', ],
		[ '\b{wb}buew', 'bij', ],
		[ '\b{wb}büw', 'bij', ],
		[ '\b{wb}Paa', 'Pa', ],
		[ '\b{wb}dhew', 'dev', ],
		[ 'deuw', 'dev', ],
		[ '\b{wb}Lueck', 'Lūg', ],
		[ 'uwa', 'uvā', ],
		[ 'wher', 'ver', ],
		[ '\b{wb}pewili', 'pieviļ', ],
		[ '\b{wb}pew', 'piev', ],
		[ '\b{wb}ewed', 'ieve', ],
		[ 'wh', '', ],
		[ 'w', 'v', ],
		[ '\b{wb}rück', 'rūg', ],
		[ '\b{wb}nü\b{wb}', 'nu', ],
		[ '\b{wb}Tüa', 'Tuvā', ],
		[ 'ã', 'a', ],
		[ '\b{wb}Vd', 'Ūd', ],
		[ '\b{wb}vs', 'uz', ],
		[ '\b{wb}vnd', 'und', ],
		[ 'tek', 'tiek', ],
		[ '\b{wb}bede', 'biede', ],
		[ '\b{wb}Dre', 'Drēb', ],
		[ '\b{wb}bes\b{wb}', 'bez', ],
		[ '\b{wb}bheck', 'bēg', ],
		[ '\b{wb}bhe', 'bē', ],
		[ '\b{wb}noladh', 'nolād', ],
		[ '\b{wb}lad', 'lād', ],
		[ '\b{wb}Adb', 'Atb', ],
		[ 'uh', 'ū', ],
		[ '\b{wb}khad\b{wb}', 'kad', ],
		[ '\b{wb}kha\b{wb}', 'kā', ],
		[ '\b{wb}mhes\b{wb}', 'mēs', ],
		[ 'ttade\b{wb}', 'tāde', ],
		[ '\b{wb}thad\b{wb}', 'tad', ],
		[ '\b{wb}thad', 'tāde', ],
		[ '\b{wb}tade\b{wb}', 'tāde', ],
		[ '\b{wb}tha\b{wb}', 'tā', ],
		[ '\b{wb}tems\b{wb}', 'tiems', ],
		[ 'tims\b{wb}', 'tiems', ],
		[ 'thems\b{wb}', 'tiems', ],
		[ '\b{wb}the\b{wb} ', 'tie', ],
		[ 'ah', 'ā', ],
		[ 'ing', 'iņ', ],
		[ 'ae', 'ā', ],
		[ 'aa', 'ā', ],
		[ '\b{wb}ekar', 'iekār', ],
		[ '\b{wb}pede', 'pied', ],
		[ '\b{wb}ped', 'pied', ],
		[ '\b{wb}pem', 'piem', ],
		[ '\b{wb}pep', 'piep', ],
		[ '\b{wb}leke\b{wb}', 'lieke', ],
		[ '\b{wb}Bicke', 'Biķ', ],
		[ '\b{wb}Bick', 'Biķ', ],
		[ '\b{wb}Otee', 'Ote', ],
		[ 'teer', 'er', ],
		[ '\b{wb}Szee', 'Žē', ],
		[ '\b{wb}Szel', 'Zel', ],
		[ '\b{wb}Sz', 's', ],
		[ '\b{wb}peaug', 'pieaug', ],
		[ '\b{wb}atees\b{wb}', 'aties', ],
		[ '\b{wb}lee', 'lie', ],
		[ 'ee', 'ē', ],
		[ '\b{wb}loud', 'ļaud', ],
		[ '\b{wb}loun', 'ļaun', ],
		[ '\b{wb}palou', 'paļau', ],
		[ '\b{wb}pallo', 'paļa', ],
		[ 'ou', 'au', ],
		[ '\b{wb}luuckt\b{wb}', 'lūgt', ],
		[ 'uu', 'ū', ],
		[ 'ue', 'i', ],
		[ 'oo', 'o', ],
		[ '\b{wb}Jure\b{wb}', 'Jūre', ],
		[ 'Jl', 'Il', ],
		[ '\b{wb}Js\b{wb}', 'Īz', ],
		[ '\b{wb}Jt', 'Īt', ],
		[ '\b{wb}Pere\b{wb}', 'Piere', ],
		[ 'kap', 'kāp', ],
		[ 'neke', 'nieke', ],
		[ '\b{wb}Sob', 'Zob', ],
		[ '\b{wb}enak', 'ienāk', ],
		[ '\b{wb}en', 'ien', ],
		[ '\b{wb}Mathe\b{wb}', 'Māte', ],
		[ '\b{wb}Mer', 'Miere', ],
		[ '\b{wb}grut', 'grūt', ],
		[ 'ath', 'āt', ],
		[ '\b{wb}beth\b{wb}', 'bet', ],
		[ '\b{wb}thi', 'tie', ],
		[ '\b{wb}Adam', 'Ādam', ],
		[ 'ada', 'āda', ],
		[ 'impt', 'imt', ],
		[ '\b{wb}Vaige\b{wb}', '#', ],	# Palīgmaiņa
		[ 'ige\b{wb}', 'īge', ],
		[ '#', 'Vaige', ],		# Palīgmaiņas novākšana
		[ 'grek', 'grēk', ],
		[ '\b{wb}luckt\b{wb}', 'lūgt', ],
		[ 'ldt', 'lt', ],
		[ 'mac', 'māc', ],
		[ 'm̃ešẽ', 'mešen', ],
		[ 'Mẽrs', 'Miers', ],
		[ 'ẽs\b{wb}', 'iems', ],
		[ 'ñ', 'n', ],
		[ '\b{wb}dabbu', 'dabū', ],
		[ 'bb', 'b', ],
		[ 'dd', 'd', ],
		[ 'igg', 'ig', ],
		[ 'gga', 'gā', ],
		[ '\b{wb}ruck', 'rūg', ],
		[ 'ck', 'k', ],
		[ '\b{wb}allas', 'a%až', ],			# Palīgmaiņa
		[ '\b{wb}Hell', 'He%', ],			# Palīgmaiņa
		[ 'll', 'l', ],
		[ '\%', 'll', ],						# Palīgmaiņas novākšana
		[ 'mm', 'm', ],
		[ '\b{wb}Anna\b{wb}', 'A#a', ],		# Palīgmaiņa
		[ 'nn', 'n', ],
		[ '\b{wb}A#a\b{wb} ', 'Anna', ],	# Palīgmaiņas novākšana
		[ 'app', 'ap', ],
		[ 'rr', 'r', ],
		[ 'tth', 't', ],
		[ 'tt', 't', ],
		[ '\b{wb}Dhel', 'Dēl', ],
		[ 'dh', 'd', ],
		[ 'nh', 'n', ],
		[ '\b{wb}Phr', 'Fr', ],
		[ 'th', 't', ],
		[ 'aia', 'āja', ],
		[ 'eia', 'ēja', ],
		[ 'oiam\b{wb}', 'jam', ],
		[ '\b{wb}bia\b{wb}', 'bija', ],
		[ 'ibes\b{wb}', 'ībes', ],
		[ 'ibe\b{wb}', 'ībe', ],
	],
	'Gis1507_PN'     => [
		[ '\b{wb}Teweß\b{wb}', 'Tēves', ],
		[ '\b{wb}müß\b{wb}', 'mūs', ],
		[ '^ka\b{wb}', 'kas', ],
		[ '\b{wb}tw\b{wb}', 'tu', ],
		[ '\b{wb}eſe\b{wb}', 'ese', ],
		[ '\b{wb}exkann\b{wb}', 'iekškan', ],
		[ '\b{wb}exkan\b{wb}', 'iekškan', ],
		[ 'bbeſyß\b{wb}', 'besīs', ],
		[ '\b{wb}ſwetyt\b{wb}', 'svētīt', ],
		[ '\b{wb}bws\b{wb}', 'būs', ],
		[ '\b{wb}bwß\b{wb}', 'būs', ],
		[ 'owß\b{wb}', 'avs', ],
		[ '\b{wb}wardß\b{wb}', 'vārds', ],
		[ '\b{wb}enna', 'ienā', ],
		[ '\b{wb}mumß\b{wb}', 'mums', ],
		[ 'ow\b{wb} ', 'av', ],
		[ '\b{wb}walſcyby\b{wb}', 'valstībī', ],
		[ 'wß\b{wb}', 'vs', ],
		[ 'aaʒ\b{wb}', 'āts', ],
		[ '\b{wb}ka\b{wb}', 'kā', ],
		[ '\b{wb}Vnnd\b{wb}', 'Und', ],
		[ '\b{wb}ſemeß\b{wb}', 'zemes', ],
		[ '\b{wb}muße\b{wb}', 'mūse', ],
		[ '\b{wb}dynyʒe\b{wb}', 'dieniske', ],
		[ 'yſ', 'iz', ],
	],
	'Gr1520_PN'      => [
		[ '\b{wb}Nosſen\b{wb}', 'Nosen', ],
		[ '\b{wb}Thew', 'Tēv', ],
		[ '\b{wb}Cur\b{wb}', 'Kur', ],
		[ '\b{wb}thu\b{wb}', 'tu', ],
		[ '\b{wb}delba', 'debe', ],
		[ '\b{wb}Zweÿtz\b{wb}', 'Svētīts', ],
		[ '\b{wb}giſcher\b{wb}', 'jir', ],
		[ '\b{wb}thow', 'tav', ],
		[ '\b{wb}war', 'vār', ],
		[ '\b{wb}Penag\b{wb}', 'Pienāk', ],
		[ '\b{wb}muni', 'mum', ],
		[ '\b{wb}Tholb ', 'Tav', ],
		[ '\b{wb}müſtlaſtil', 'valstī', ],
		[ '\b{wb}Tolp', 'Tav', ],
		[ 'atr', 'āt', ],
		[ '\b{wb}Girkad', 'Jir kād', ],
		[ '\b{wb}delbesſi', 'debesī', ],
		[ '\b{wb}tad', 'tād', ],
		[ '\b{wb}Sÿmm', 'Zīm', ],
		[ '\b{wb}Semm', 'Zem', ],
		[ '\b{wb}Worsünÿ\b{wb}', 'Virsūnī', ],
		[ '\b{wb}mommÿs\b{wb}', 'mums', ],
		[ '\b{wb}Annosse\b{wb}', 'Anosen', ],
		[ '\b{wb}igdem', 'ikdien', ],
		[ 'ÿs', 'iz', ],
		[ '\b{wb}Gaÿtk', 'Gaitk', ],
		[ 'mm', 'm', ],
		[ '\b{wb}mumÿs\b{wb}', 'mums', ],
		[ '\b{wb}nusſe\b{wb}', 'nuse', ],
		[ 'zeg', 'zieg', ],
		[ '\b{wb}Cademes\b{wb}', 'Kāde mēs', ],
		[ '\b{wb}mus', 'mūs', ],
		[ 'taune kans\b{wb}', 'iniekam', ],
		[ 'we', 've', ],
		[ '\b{wb}law', 'ļau', ],
		[ '\b{wb}Swal', 'Sva', ],
		[ '\b{wb}nowusſe\b{wb}', 'no vis', ],
		[ '\b{wb}Loy', 'Ļau', ],
		[ '\b{wb}Jes', 'Jēz', ],
		[ '\b{wb}Amen\b{wb}', 'Āmen', ],
	],
	'Has1550_PN'  => [
		[ '\b{wb}Täb', 'Tēv', ],
		[ '\b{wb}mus\b{wb}', 'mūs', ],
		[ '\b{wb}muß', 'mūs', ],
		[ '\b{wb}meß\b{wb}', 'mēs', ],
		[ '\b{wb}eckſch', 'iekš', ],
		[ 'bb', 'b', ],
		[ 'ſſ', 's', ],
		[ '\b{wb}Schwetitz\b{wb}', 'Švētīts', ],
		[ 'ow', 'av', ],
		[ '\b{wb}waartz\b{wb}', 'vārds', ],
		[ '\b{wb}enac', 'ienā', ],
		[ '\b{wb}walſti', 'valstī', ],
		[ 'aa', 'ā', ],
		[ '\b{wb}bus\b{wb}', 'būs', ],
		[ '\b{wb}ka\b{wb}', 'kā', ],
		[ '\b{wb}ta\b{wb}', 'tā', ],
		[ '\b{wb}wurſ', 'virs', ],
		[ '\b{wb}ſemm', 'zem', ],
		[ '\b{wb}Muſſ', 'Mūs', ],
		[ '\b{wb}deniſch', 'dienisk', ],
		[ 'äyſ', 'aiz', ],
		[ '\b{wb}důth\b{wb}', 'dot', ],
		[ '\b{wb}wü', 'vi', ],
		[ 'ü', 'u', ],
		[ 'ß', 's', ],
		[ '\b{wb}ſchode', 'šodi', ],
		[ 'mma', 'me', ],
		[ '\b{wb}grä', 'grē', ],
		[ 'radu', 'ādni', ],
		[ '\b{wb}wed', 've', ],
		[ '\b{wb}lou', 'ļau', ],
		[ 'ck', 'k', ],
		[ '\b{wb}pett\b{wb}', 'bet', ],
		[ '\b{wb}nu\b{wb}', 'no', ],
		[ '\b{wb}Amen\b{wb}', 'Āmen', ],
	],
	'Laz1557_PN'  => [
		[ '\b{wb}tab', 'tēv', ],
		[ '\b{wb}MVs\b{wb}', 'MŪs', ],
		[ '\b{wb}tV\b{wb}', 'tU', ],
		[ '\b{wb}eckSch', 'iekŠ', ],
		[ 'bb', 'b', ],
		[ 'ssi', 'si', ],
		[ '\b{wb}schvvetitz\b{wb}', 'švētīts', ],
		[ '\b{wb}tov', 'ta', ],
		[ 'vaarcz\b{wb}', 'ārds', ],
		[ '\b{wb}ENAK\b{wb}', 'IENĀK', ],
		[ '\b{wb}MV', 'MU', ],
		[ '\b{wb}vva', 'va', ],
		[ 'aatz\b{wb}', 'āts', ],
		[ '\b{wb}bvs\b{wb}', 'būs', ],
		[ '\b{wb}ka\b{wb}', 'kā', ],
		[ '\b{wb}ecksch', 'iekš', ],
		[ '\b{wb}ta\b{wb}', 'tā', ],
		[ '\b{wb}vvvr', 'vir', ],
		[ '\b{wb}svm', 'ze', ],
		[ '\b{wb}Mvs', 'Mū', ],
		[ '\b{wb}denisch', 'dienisk', ],
		[ 'ys', 'iz', ],
		[ '\b{wb}dvth\b{wb}', 'dot', ],
		[ '\b{wb}schod', 'šodi', ],
		[ 'mma', 'me', ],
		[ '\b{wb}mvm', 'mum', ],
		[ '\b{wb}mvss', 'mūs', ],
		[ '\b{wb}gra', 'grē', ],
		[ '\b{wb}mess\b{wb}', 'mēs', ],
		[ '\b{wb}mvs\b{wb}', 'mūs', ],
		[ 'tradv', 'rādni', ],
		[ '\b{wb}vved', 've', ],
		[ '\b{wb}lov', 'ļau', ],
		[ 'ck', 'k', ],
		[ '\b{wb}pett\b{wb}', 'bet', ],
		[ 'sarz', 'arg', ],
		[ '\b{wb}nv\b{wb}', 'no', ],
		[ '\b{wb}vvvs', 'vi', ],
		[ '\b{wb}Amen\b{wb}', 'Āmen', ],
	],
	'Manc1631_LGL' => [
		[ '\b{wb}David', 'Dawid', ],
		[ '\b{wb}vß', 'u%', ],	# Palīgmaiņa
		[ '\b{wb}Vß', 'U%', ],	# Palīgmaiņa
		[ 'Vh', 'Ū', ],
		[ 'V', 'U', ],
		[ 'v', 'u', ],
		[ 'Tſch', 'Č', ],
		[ 'tſchſ', 'č', ],
		[ 'ſchläl', 'žēl', ],
		[ 'ſſchan', 'šan', ],
		[ 'ſchan', 'šan', ],
		[ 'ſpohſch', 'spož', ],
		[ '\b{wb}Spohſch', 'Spož', ],
		[ 'laiſch', 'laiž', ],
		[ '\b{wb}Ghaiſch', 'Gaiš', ],
		[ 'ghaiſch', 'gaiš', ],
		[ 'ghaiſſch', 'gaiš', ],
		[ '\b{wb}Ghaiſſch', 'Gaiš', ],
		[ '\b{wb}wiſchk', 'višk', ],
		[ '\b{wb}wiſchſk', 'višk', ],
		[ '\b{wb}muiſchn', 'muižn', ],
		[ '\b{wb}Scheiſchinny\b{wb}', 'Šeišinī', ],
		[ 'iſch', 'īš', ],
		[ '\b{wb}Balloſch', 'Balož', ],
		[ 'noſchaw', 'nožāv', ],
		[ 'oſch', 'oš', ],
		[ 'ohſch', 'oš', ],
		[ '\b{wb}muhſchig', 'mūžīg', ],
		[ '\b{wb}muſchig', 'mūžīg', ],
		[ 'yuſch', 'juš', ],
		[ 'ļauſch', 'ļauž', ],
		[ '\b{wb}Ļauſch', 'Ļauž', ],
		[ 'ghauſch', 'gauž', ],
		[ 'ſchauſch', 'šauš', ],
		[ 'uſch', 'uš', ],
		[ 'yuſſch', 'juš', ],
		[ 'uſſch', 'uš', ],
		[ '\b{wb}allaſch', 'a#až', ],	# Palīgmaiņa
		[ '\b{wb}Allaſch', 'A#až', ],	# Palīgmaiņa
		[ '\b{wb}appakſch', 'apakš', ],
		[ '\b{wb}auhſch', 'auš', ],
		[ '\b{wb}aukſch', 'augš', ],
		[ '\b{wb}Aukſch', 'Augš', ],
		[ '\b{wb}AVkſch', 'AUgš', ],
		[ '\b{wb}czellſch\b{wb}', 'ceļš', ],
		[ 'czeeſch', 'c&š', ],	# Palīgmaiņa
		[ 'czienieſch', 'cīnīš', ],
		[ '\b{wb}Daſſch\b{wb}', 'Dažs', ],
		[ '\b{wb}daſſch\b{wb}', 'dažs', ],
		[ '\b{wb}drohſſch', 'droš', ],
		[ '\b{wb}Dwaſſcha', 'Dvaša', ],
		[ 'eekſch', '&kš', ],	# Palīgmaiņa
		[ '\b{wb}Ehrſſch', 'Ērš', ],
		[ '\b{wb}Ehrſch', 'Ērš', ],
		[ '\b{wb}Eſch', 'Eš', ],
		[ '\b{wb}gharrſch', 'garš', ],
		[ '\b{wb}jebſch', 'jebš', ],
		[ '\b{wb}Jebſch', 'Jebš', ],
		[ '\b{wb}Karraſch', 'Karaš', ],
		[ '\b{wb}Karrſch', 'Karš', ],
		[ 'llickſch', 'likš', ],
		[ 'mellſch', 'melš', ],
		[ 'nahkſch', 'nākš', ],
		[ 'niekſchk', 'nīkšķ', ],
		[ 'Ghaſpaſch', 'Gaspaž', ],
		[ '\b{wb}paſch', 'paš', ],
		[ '\b{wb}paſſch', 'paš', ],
		[ '\b{wb}Pieſch', 'Pīš', ],
		[ 'pleſſch', 'pleš', ],
		[ 'puhſch', 'pūš', ],
		[ '\b{wb}Puyſſch', 'Puiš', ],
		[ 'puſſch', 'puš', ],
		[ 'raſſch', 'raš', ],
		[ '\b{wb}rupſch\b{wb}', 'rupš', ],
		[ '\b{wb}ſchad', ' šād', ],
		[ '\b{wb}ſchah', 'šā', ],
		[ '\b{wb}ſchai', 'šai', ],
		[ '\b{wb}ſchauſſchal', 'šaušal', ],
		[ '\b{wb}Schauſſchal', 'Šaušal', ],
		[ 'ſchau', 'šau', ],
		[ '\b{wb}ſchee', 'š&', ],	# Palīgmaiņa
		[ '\b{wb}ſcheit', 'šeit ', ],
		[ '\b{wb}ſchenn', 'šen', ],
		[ '\b{wb}ſchi', 'ši', ],
		[ 'ſchlaw', 'slav', ],
		[ 'ſchlehp', 'slēp', ],
		[ '\b{wb}ſcho', 'šo', ],
		[ '\b{wb}ſchurr', 'šur', ],
		[ '\b{wb}ſchurp\b{wb}', 'šurp', ],
		[ '\b{wb}ſchy\b{wb}', 'šī', ],
		[ '\b{wb}ſchweſſch', 'sveš', ],
		[ '\b{wb}ſmillſch', 'smilš', ],
		[ '\b{wb}ſwäſſcho', 'sveš', ],
		[ '\b{wb}ſweſſch', 'sveš', ],
		[ '\b{wb}ẜeſſch', 'seš', ],
		[ '\b{wb}teeſch', 't&š', ],	# Palīgmaiņa
		[ '\b{wb}treſſch', 'treš', ],
		[ '\b{wb}Treſſch', 'Treš', ],
		[ 'tuckſch', 'tukš', ],
		[ '\b{wb}Wehſch', 'Vējš', ],
		[ '\b{wb}Wehrſch', 'Vērš', ],
		[ 'wiſſaſchk', 'visašķ', ],
		[ 'wiſẜaſchk', 'visašķ', ],
		[ '\b{wb}Ꞩeſſchi\b{wb}', 'Seši', ],
		[ '\b{wb}Queeſch', 'Kv&š', ],	# Palīgmaiņa
		[ 'ſchäl', 'žēl', ],
		[ 'ſchähl', 'žēl', ],
		[ 'daſchatz', 'dažāΔ', ],
		[ 'ſch', 'ž', ],
		[ '\b{wb}Ꞩirdtz', 'SirΔ', ],	# Palīgmaiņa
		[ '\b{wb}Gohdtz\b{wb}', 'GoΔ', ],	# Palīgmaiņa
		[ 'ſlietz', 'slīc', ],
		[ 'lietz', 'līΔ', ],	# Palīgmaiņa
		[ 'ietz', 'īts', ],
		[ 'ſwähtz', 'svēts', ],
		[ '\b{wb}Swähtz\b{wb}', 'Svēts', ],
		[ '\b{wb}Prahtz\b{wb}', 'Prāts', ],
		[ '\b{wb}tahtz\b{wb}', 'tāΔ', ],	# Palīgmaiņa
		[ 'maitahtz\b{wb}', 'maitāts', ],
		[ 'attſtahtz\b{wb}', 'atstāts', ],
		[ '\b{wb}Schultz\b{wb}', 'Žults', ],
		[ '\b{wb}Autz\b{wb}', 'Auts', ],
		[ 'liktz\b{wb}', 'likts', ],
		[ 'ẜarrghahtz\b{wb}', 'sargāts', ],
		[ '\b{wb}Wahrdtz\b{wb}', 'VārΔ', ],	# Palīgmaiņa
		[ 'ähtz\b{wb}', 'ēts', ],
		[ 'runnahtz\b{wb}', 'runāts', ],
		[ 'patz\b{wb}', 'pats', ],
		[ 'kahtz\b{wb}', 'kāΔ', ],	# Palīgmaiņa
		[ 'jämbtz\b{wb}', 'jemts', ],
		[ 'ẜiſtz\b{wb}', 'sists', ],
		[ 'racktz\b{wb}', 'rakts', ],
		[ 'taptz\b{wb}', 'tapts', ],
		[ 'dahtz\b{wb}', 'dāts', ],
		[ '\b{wb}Ghohdtz\b{wb}', 'GoΔ', ],	# Palīgmaiņa
		[ '\b{wb}Sirrdtz\b{wb}', 'SirΔ', ],	# Palīgmaiņa
		[ '\b{wb}Sirdtz\b{wb}', 'SirΔ', ],	# Palīgmaiņa
		[ '\b{wb}Ꞩirrdtz\b{wb}', 'SirΔ', ],	# Palīgmaiņa
		[ 'ẜilltz\b{wb}', 'silts', ],
		[ '\b{wb}baggahtz\b{wb}', 'bagāts', ],
		[ 'dohtz\b{wb}', 'dots', ],
		[ 'enahtz\b{wb}', 'enāts', ],
		[ 'nacktz', 'nakts', ],
		[ '\b{wb}Ghohtz\b{wb}', 'GoΔ', ],	# Palīgmaiņa
		[ '\b{wb}Awohtz\b{wb}', 'Avots', ],
		[ '\b{wb}Swetz\b{wb}', 'Svēts', ],
		[ 'ghrautz\b{wb}', 'grauΔ', ],	# Palīgmaiņa
		[ 'äſẜohtz\b{wb}', 'esots', ],
		[ 'ghohtz\b{wb}', 'goΔ', ],	# Palīgmaiņa
		[ '\b{wb}Nacktz\b{wb}', 'Nakts', ],
		[ 'ihtz\b{wb}', 'īts', ],
		[ '\b{wb}Ghodtz\b{wb}', 'GoΔ', ],	# Palīgmaiņa
		[ '\b{wb}Wahrtz\b{wb}', 'VārΔ', ],	# Palīgmaiņa
		[ 'auxtz\b{wb}', 'augsts', ],
		[ '\b{wb}Auxtz\b{wb}', 'Augsts', ],
		[ 'mbtz\b{wb}', 'mts', ],
		[ 'licktz\b{wb}', 'likts', ],
		[ '\b{wb}Ghadtz\b{wb}', 'GaΔ', ],	# Palīgmaiņa
		[ '\b{wb}Tahtz\b{wb}', 'TāΔ', ],	# Palīgmaiņa
		[ 'ẜahwahtz\b{wb}', 'savāΔ', ],	# Palīgmaiņa
		[ 'währtz\b{wb}', 'vērts', ],
		[ 'yohtz\b{wb}', 'jots', ],
		[ 'ẜaudtz', 'sauc', ],
		[ 'kalltz\b{wb}', 'kalts', ],
		[ 'kahrtz\b{wb}', 'kārts', ],
		[ 'kautz\b{wb}', 'kauts', ],
		[ 'pullgohtz\b{wb}', 'pulgots', ],
		[ 'wahtz\b{wb}', 'vāts', ],
		[ '\b{wb}Gohtz\b{wb}', 'GoΔ', ],	# Palīgmaiņa
		[ '\b{wb}Ꞩirtz\b{wb}', 'SirΔ', ],	# Palīgmaiņa
		[ '\b{wb}ſmeetz\b{wb}', 'sm&ts', ],	# Palīgmaiņa
		[ 'neewahtz\b{wb}', 'n&vāts', ],	# Palīgmaiņa
		[ 'tärptz\b{wb}', 'tērpts', ],
		[ 'kulltz\b{wb}', 'kults', ],
		[ 'kohtz\b{wb}', 'ķots', ],
		[ 'dähwahtz\b{wb}', 'dēvāts', ],
		[ 'klahtz\b{wb}', 'klāts', ],
		[ 'ſwahtz\b{wb}', 'svēts', ],
		[ '\b{wb}Atz', 'Ac', ],
		[ '\b{wb}Pirxtz\b{wb}', 'Pirksts', ],
		[ '\b{wb}Ahwohtz\b{wb}', 'Avots', ],
		[ 'dſimtz\b{wb}', 'dsimts', ],
		[ 'prahtz\b{wb}', 'prāts', ],
		[ '\b{wb}Radtz\b{wb}', 'RaΔ', ],	# Palīgmaiņa
		[ 'raddietz\b{wb}', 'radīts', ],
		[ 'nitzinahtz\b{wb}', 'nicināts', ],
		[ 'dehtz\b{wb}', 'dēts', ],
		[ 'ẜahktz\b{wb}', 'sākts', ],
		[ '\b{wb}Seedtz\b{wb}', '%&Δ', ],	# Palīgmaiņa
		[ 'pedtz', 'pēc', ],
		[ 'pehtz\b{wb}', 'pēc', ],
		[ '\b{wb}Titz', 'Tic', ],
		[ 'nahtz', 'nāc', ],
		[ '\b{wb}Ꞩirrtz\b{wb}', 'SirΔ', ],	# Palīgmaiņa
		[ '\b{wb}Ꞩlawätz\b{wb}', 'Slavēts', ],
		[ 'czittz', 'cits', ],
		[ 'wayahtz\b{wb}', 'vajāts', ],
		[ 'ghribbohtz\b{wb}', 'gribots', ],
		[ 'deßmittz\b{wb}', 'desmits', ],
		[ 'pattz', 'pats', ],
		[ 'ẜirdtz', 'sirΔ', ],	# Palīgmaiņa
		[ 'czitttz', 'cits', ],
		[ 'gohtz\b{wb}', 'goΔ', ],	# Palīgmaiņa
		[ 'leetz', 'l&c', ],	# Palīgmaiņa
		[ 'titz', 'tic', ],
		[ 'tumſẜohtz\b{wb}', 'tumsots', ],
		[ 'dohdtz\b{wb}', 'dots', ],
		[ 'baggatz\b{wb}', 'bagāts', ],
		[ 'bagghatz\b{wb}', 'bagāts', ],
		[ 'teicktz\b{wb}', 'teikts', ],
		[ '\b{wb}Sältz\b{wb}', '%elts', ],	# Palīgmaiņa
		[ 'czälltz\b{wb}', 'celts', ],
		[ 'äßmohtz\b{wb}', 'esmots', ],
		[ 'tz', 'c', ],
		[ 'czh', 'ģ', ],
		[ '\b{wb}Czh', 'Ģ', ],
		[ 'cz', 'c', ],
		[ 'CZ', 'C', ],
		[ '\b{wb}Cz', 'C', ],
		[ 'dz', 'Δ', ],	# Palīgmaiņa
		[ 'z', 'c', ],
		[ 'Z', 'C', ],
		[ '\%', 'z', ],	# Palīgmaiņas novākšana
		[ 'dſ', 'dz', ],
		[ 'Dſ', 'Dz', ],
		[ 'ds', 'dz', ],
		[ 'Δ', 'ds', ],	# Palīgmaiņas novākšana
		[ 'ſſ', 's', ],
		[ 'ſp', 'sp', ],
		[ 'ſkumm', 'skum', ],
		[ 'ſkatt', 'skat', ],
		[ 'ſkaidr', 'skaidr', ],
		[ 'ſkraid', 'skraid', ],
		[ 'aiſk', 'aizsk', ],
		[ 'ſkubb', 'skub', ],
		[ 'ſkann', 'skan', ],
		[ 'ſkanņ', 'skaņ', ],
		[ 'ſkuhp', 'skūp', ],
		[ 'ſkai', 'skai', ],
		[ 'ſkaud', 'skaud', ],
		[ 'ſkum', 'skum', ],
		[ 'ſkrand', 'skrand', ],
		[ '\b{wb}Pieſkop', 'Pīskop', ],
		[ 'ſkrey', 'skrej', ],
		[ 'ſk', 'šķ', ],
		[ 'ſl', 'sl', ],
		[ 'aiſm', 'aizm', ],
		[ 'ſm', 'sm', ],
		[ 'aiſto', 'aizto', ],
		[ '\b{wb}Aiſ', 'Aiz', ],
		[ 'ſt', 'st', ],
		[ 'ſwäh', 'svē', ],
		[ 'ſwä', 'svē', ],
		[ 'ſwah', 'svē', ],
		[ 'ſwehr', 'zvēr', ],
		[ 'ſw', 'sv', ],
		[ 'ſẜ', 's', ],
		[ 'ſackt', 'zagt', ],
		[ '\b{wb}ſah', 'sā', ],
		[ '\b{wb}ſa', 'sa', ],
		[ 'ſöw', 'sev', ],
		[ 'tapſi', 'tapsi', ],
		[ 'ſitt', 'sit', ],
		[ 'ſehd', 'sēd', ],
		[ 'ſäd', 'sēd', ],
		[ 'ſohl', 'sol', ],
		[ '\b{wb}ſuh', 'sū', ],
		[ 'pſ', 'ps', ],
		[ 'taiſn', 'taisn', ],
		[ 'wehrſ', 'vērs', ],
		[ 'ſiß', 'sis', ],
		[ '\b{wb}ſeh', 'sē', ],
		[ 'ſak', 'sāk', ],
		[ 'ſ', 'z', ],
		[ '\b{wb}Sämm', 'Zem', ],
		[ '\b{wb}Semm', 'Zem', ],
		[ '\b{wb}Siem', 'Zīm', ],
		[ '\b{wb}Siež', 'Zīž', ],
		[ '\b{wb}Swahrg', 'Zvārg', ],
		[ '\b{wb}Sällt', 'Zelt', ],
		[ '\b{wb}Sält', 'Zelt', ],
		[ '\b{wb}Sem̃', 'Zem', ],
		[ '\b{wb}Swaigs', 'Zvaigz', ],
		[ 'svaigsn', 'zvaigzn', ],
		[ '\b{wb}Swaig', 'Zvaig', ],
		[ '\b{wb}Sarr', 'Zar', ],
		[ '\b{wb}Sagg', 'Zag', ],
		[ '\b{wb}Swehr', 'Zvēr', ],
		[ '\b{wb}Sackt', 'Zagt', ],
		[ '\b{wb}Sinna', 'Zinā', ],
		[ '\b{wb}Sahl', 'Zāl', ],
		[ '\b{wb}Swär', 'Zvēr', ],
		[ '\b{wb}Sizlis', 'Zizlis', ],
		[ '\b{wb}Sob', 'Zob', ],
		[ '\b{wb}Sohb', 'Zob', ],
		[ '\b{wb}Sied', 'Zīd', ],
		[ '\b{wb}Swähr', 'Zvēr', ],
		[ '\b{wb}Siw', 'Ziv', ],
		[ '\b{wb}Sirr', 'Zir', ],
		[ 'dẜ', 'dz', ],
		[ 'ẜchehl', 'žēl', ],
		[ 'ẜch', 'š', ],
		[ 'ẜ', 's', ],
		[ 'Ꞩch', 'Š', ],
		[ '\b{wb}Ꞩämm', 'Zem', ],
		[ 'Ꞩ', 'S', ],
		[ '\b{wb}Schäl', 'Žēl', ],
		[ '\b{wb}Schull', 'Žul', ],
		[ '\b{wb}Schohg', 'Žog', ],
		[ '\b{wb}Sch', 'Š', ],
		[ '\b{wb}iß', 'iz', ],
		[ '\b{wb}Jß', 'Iz', ],
		[ 'aißläh', 'aizslē', ],
		[ '\b{wb}aiß', 'aiz', ],
		[ '\b{wb}beß', 'bez', ],
		[ '\b{wb}Beß', 'Bez', ],
		[ '\b{wb}Jhß', 'Īz', ],
		[ '\b{wb}ihß', 'īz', ],
		[ 'ß', 's', ],
		[ '\b{wb}by\b{wb}', 'bij', ],
		[ '\b{wb}By\b{wb}', 'Bij', ],
		[ '\b{wb}py\b{wb}', 'pi', ],
		[ '\b{wb}Py\b{wb}', 'Pi', ],
		[ 'ya', 'ja', ],
		[ 'yi', 'ji', ],
		[ 'nyu', 'ņu', ],
		[ 'rryu', 'ŗu', ],
		[ 'ryu', 'ŗu', ],
		[ 'yu', 'ju', ],
		[ 'yee', 'j&', ],	# Palīgmaiņa
		[ 'tyer', 'tīr', ],
		[ 'bye', 'bī', ],
		[ 'mye', 'mī', ],
		[ '\b{wb}Rye', 'Rī', ],
		[ 'yeh', 'jē', ],
		[ 'ye', 'je', ],
		[ '\b{wb}tay\b{wb}', 'tai', ],
		[ '\b{wb}Tay', 'Tai', ],
		[ '\b{wb}way', 'vai', ],
		[ '\b{wb}Way', 'Vai', ],
		[ 'bayl', 'bail', ],
		[ 'ay', 'aj', ],
		[ 'ahy', 'āj', ],
		[ 'oy', 'oj', ],
		[ 'ey', 'ej', ],
		[ 'Ey', 'Ej', ],
		[ 'uy', 'uj', ],
		[ 'iy', 'ij', ],
		[ 'rryo', 'ŗo', ],
		[ 'ryo', 'ŗo', ],
		[ '\b{wb}Karryà', 'Kaŗā', ],
		[ 'nyo', 'ņu', ],
		[ 'yo', 'jo', ],
		[ 'ehy', 'ēj', ],
		[ 'myrr', 'mir', ],
		[ 'yh', 'ī', ],
		[ 'yä', 'je', ],
		[ 'y', 'ī', ],
		[ 'Y', 'Ī', ],
		[ 'äh', 'ē', ],
		[ 'Äh', 'Ē', ],
		[ '\b{wb}Wäll', 'Ve#', ],	# Palīgmaiņa
		[ '\b{wb}Mäll', 'Me#', ],	# Palīgmaiņa
		[ 'ä', 'e', ],
		[ 'Ä', 'E', ],
		[ 'max', 'max', ],
		[ '\b{wb}Kunx', 'Kungs', ],
		[ '\b{wb}Palliex', 'Palīgs', ],
		[ 'deewiex', 'd&vīgs', ],	# Palīgmaiņa
		[ '\b{wb}Sirx', 'Zirgs', ],
		[ '\b{wb}Waix', 'Vaigs', ],
		[ 'leex', 'l&gs', ],	# Palīgmaiņa
		[ 'lehniex', 'lēnīgs', ],
		[ 'walldiex', 'valdīgs', ],
		[ 'nabbax', 'nabags', ],
		[ 'iex\b{wb}', 'īgs', ],
		[ '\b{wb}Draux', 'Draugs', ],
		[ 'dahrx', 'dārgs', ],
		[ '\b{wb}Sneex', 'Sn&gs', ],	# Palīgmaiņa
		[ 'prahtiex', 'pratīgs', ],
		[ '\b{wb}KVnx', 'KUngs', ],
		[ '\b{wb}Meex', 'M&gs', ],	# Palīgmaiņa
		[ 'irx', 'irgs', ],
		[ 'ddex', 'degs', ],
		[ 'dex', 'degs', ],
		[ 'barrx', 'bargs', ],
		[ 'kunx', 'kungs', ],
		[ 'nabbahx', 'nabags', ],
		[ 'darx', 'dārgs', ],
		[ '\b{wb}Waiņax', 'Vaiņags', ],
		[ 'behx', 'bēgs', ],
		[ '\b{wb}Wainax', 'Vainags', ],
		[ '\b{wb}Wallx', 'Valgs', ],
		[ 'auxt', 'augst', ],
		[ '\b{wb}Auxt', 'Augst', ],
		[ 'x', 'ks', ],
		[ 'ie', 'ī', ],
		[ '\&', 'ie', ],	# Palīgmaiņas novākšana
		[ 'Eee', 'Ie', ],
		[ 'ee', 'ie', ],
		[ 'Ee', 'Ie', ],
		[ 'bh', 'b', ],
		[ 'bb', 'b', ],
		[ 'ck', 'k', ],
		[ 'dt', 't', ],
		[ 'dd', 'd', ],
		[ 'eh', 'ē', ],
		[ 'Eh', 'Ē', ],
		[ 'gh', 'g', ],
		[ 'gg', 'g', ],
		[ 'Gh', 'G', ],
		[ 'gir', 'jir', ],
		[ 'Gir', 'Jir', ],
		[ 'ah', 'ā', ],
		[ 'Ah', 'Ā', ],
		[ 'à', 'ā', ],
		[ 'ih', 'ī', ],
		[ 'ņj', 'ņ', ],
		[ 'Ell', 'E#', ],	# Palīgmaiņa
		[ 'pilla', 'pi#a', ],	# Palīgmaiņa
		[ 'll', 'l', ],
		[ '\#', 'll', ],	# Palīgmaiņas novākšana
		[ 'ļļ', 'ļ', ],
		[ 'mm', 'm', ],
		[ 'mb', 'm', ],
		[ 'ñ', 'n', ],
		[ 'nh', 'n', ],
		[ 'Nh', 'N', ],
		[ 'nn', 'n', ],
		[ 'ings', 'iņš', ],
		[ 'ingj', 'iņ', ],
		[ 'ing', 'iņ', ],
		[ 'W', 'V', ],
		[ 'w', 'v', ],
		[ 'oh', 'o', ],
		[ 'Oh', 'O', ],
		[ '\b{wb}Kön', 'Ķēn', ],
		[ 'ö', 'e', ],
		[ 'Ö', 'E', ],
		[ 'th', 't', ],
		[ 'Th', 'T', ],
		[ 'rr', 'r', ],
		[ 'tt', 't', ],
		[ 'uh', 'ū', ],
		[ 'pp', 'pp', ],
		[ 'Chr', 'Kr', ],
		[ 'CHr', 'Kr', ],
		[ 'SCh', 'Š', ],
		[ '\b{wb}OCk\b{wb}', 'Ok', ],
		[ 'ë', 'e', ],
		[ 'Ais', 'Aiz', ],
		[ '\b{wb}aisiet', 'aizsiet', ],
		[ '\b{wb}ais', 'aiz', ],
		[ 'besspecig', 'bezspēcīg', ],
		[ 'ss', 's', ],
		[ 'Mh', 'M', ],
		[ 'vh', 'v', ],
		[ 'nj', 'ņ', ],
		[ 'JES', 'JEZ', ],
		[ 'Qu', 'Kv', ],
	],
	'Manc1637_Sal' => [
		[ '\b{wb}daſſch\b{wb}', 'dažs', ],
		[ '\b{wb}daſch', 'daž', ],
		[ 'muhſch', 'mūž', ],
		[ '\b{wb}muſch', 'mūž', ],
		[ 'allaſch', 'a%až', ],	# Palīgmaiņa
		[ '\b{wb}ghauſch', 'gauž', ],
		[ '\b{wb}ļauſch', 'ļauž', ],
		[ 'abſchäl', 'apžēl', ],
		[ 'ſchäl', 'žēl', ],
		[ 'ſchehl', 'žēl', ],
		[ 'ſchel', 'žēl', ],
		[ 'schäl', 'žēl', ],
		[ 'schehl', 'žēl', ],
		[ 'ſchähl', 'žēl', ],
		[ 'ẜehſch', 'sēž', ],
		[ 'ſehſch', 'sēž', ],
		[ 'dadſch', 'dadž', ],
		[ 'ghreeſch', 'gr#ž', ],
		[ 'blehſch', 'blēž', ],
		[ '\b{wb}eſch', 'ež', ],
		[ '\b{wb}ehſch', 'ež', ],
		[ 'raſch', 'raž', ],
		[ 'breeſcha', 'br#ža', ],
		[ 'lauſch', 'lauž', ],
		[ 'ghruhſch', 'grūž', ],
		[ 'ſpeeſch', 'sp#ž', ],
		[ 'kohſch', 'kož', ],
		[ 'johſch', 'jož', ],
		[ 'ſẜch', 'š', ],
		[ 'ſẜ', 's', ],
		[ 'ſſch', 'š', ],
		[ 'ẜſch', 'š', ],
		[ 'schaß', 'šās', ],
		[ 'schk', 'šķ', ],
		[ 'schw', 'sw', ],
		[ 'sch', 'š', ],
		[ 'tattſche', 'taču', ],
		[ 'tſch', 'č', ],
		[ 'aukſch', 'augš', ],
		[ 'luhkſch', 'lūgš', ],
		[ 'preekſha', 'pr#kšā', ],
		[ 'ſchk', 'šķ', ],
		[ 'ſch', 'š', ],
		[ 'ẜch', 'š', ],
		[ 'dẜ', 'd&', ],	# Palīgmaiņa
		[ 'ẜäds', 'sed&', ],	# Palīgmaiņa
		[ 'ẜuhds', 'sūd&', ],	# Palīgmaiņa
		[ 'lieds', 'līd&', ],	# Palīgmaiņa
		[ 'leeds', 'l#d&', ],	# Palīgmaiņa
		[ 'neds', 'ned&', ],	# Palīgmaiņa
		[ 'dauds', 'daud&', ],	# Palīgmaiņa
		[ 'räds', 'red&', ],	# Palīgmaiņa
		[ 'ſneeds', 'sn#d&', ],	# Palīgmaiņa
		[ 'sirr', '&ir', ],	# Palīgmaiņa
		[ 'Ꞩirrtz', 'sirds', ],
		[ 'ẜirrtz', 'sirds', ],
		[ 'wahrtz', 'wārds', ],
		[ 'ghohtz', 'gods', ],
		[ 'ghohdtz', 'gods', ],
		[ 'ghodz', 'gods', ],
		[ 'ghotz', 'gods', ],
		[ 'kahtz', 'kāds', ],
		[ '\b{wb}tahtz\b{wb}', 'tāds', ],
		[ 'blehtz', 'blēds', ],
		[ 'prahtz', 'prāts', ],
		[ 'nacktz', 'nakts', ],
		[ 'peewilltz', 'p#wilts', ],	# Palīgmaiņa
		[ 'noẜauktz', 'nosaukts', ],
		[ 'ẜaseetz', 'sas#ts', ],	# Palīgmaiņa
		[ 'ẜayämbtz', 'sajemts', ],
		[ 'ẜatwärrtz', 'satwerts', ],
		[ 'pahrwährtz', 'pārwērts', ],
		[ 'ẜatzitz', 'sacīts', ],
		[ 'teicktz', 'teikts', ],
		[ 'jauktz', 'jaukts', ],
		[ 'wäßtz', 'wests', ],
		[ 'kulltz', 'kults', ],
		[ 'nheghanntz', 'negants', ],
		[ 'zälltz', 'celts', ],
		[ 'patz', 'pats', ],
		[ 'pattz', 'pats', ],
		[ 'zittz', 'cits', ],
		[ 'strautz', 'strauts', ],
		[ 'sälltz', '&elts', ],	# Palīgmaiņa
		[ 'sältz', '&elts', ],	# Palīgmaiņa
		[ 'ẜalltz', 'salds', ],
		[ '\b{wb}atz\b{wb}', 'acs', ],
		[ 'ohtz\b{wb}', 'ots', ],
		[ 'ietz\b{wb} ', 'īts', ],
		[ '\b{wb}nahtz\b{wb}', 'nāc', ],
		[ 'ahtz\b{wb}', 'āts', ],
		[ 'atz\b{wb}', 'āts', ],
		[ '\b{wb}brähtz\b{wb}', 'brēc', ],
		[ 'ähtz\b{wb}', 'ēts', ],
		[ 'auxtz', 'augsts', ],
		[ '\b{wb}wätz\b{wb}', 'wecs', ],
		[ 'tz', 'c', ],
		[ 'z', 'c', ],
		[ '\&', 'z', ],	# Palīgmaiņas novākšana
		[ 'ẜ', 's', ],
		[ 'säll', 'zel', ],
		[ 'sämm', 'zem', ],
		[ 'semm', 'zem', ],
		[ 'sahl', 'zāl', ],
		[ 'sied', 'zīd', ],
		[ 'sohb', 'zob  ', ],
		[ 'sob', 'zob', ],
		[ '\b{wb}seem', 'z#m', ],
		[ 'sinn', 'zin', ],
		[ 'sagg', 'zag', ],
		[ 'sackta', 'zagta', ],
		[ 'swirrgsdo', 'zwirgzdu', ],
		[ '\b{wb}mais\b{wb}', 'maiz', ],
		[ 'ſkieſt', 'šķīst', ],
		[ 'skieſt', 'šķīst', ],
		[ 'ſkeet', 'šķ#t', ],
		[ 'Hiſkia', 'Hiskia', ],
		[ 'ſki', 'šķi', ],
		[ 'ſſ', 's', ],
		[ 'ſackt', 'zagt', ],
		[ 'ſaim', 'zaim', ],
		[ 'ſaļļ', 'zaļ', ],
		[ '\b{wb}ſa', 'sa', ],
		[ 'ißniex', 'iznīks', ],
		[ 'notiex', 'notiks', ],
		[ 'iex\b{wb}', 'īgs', ],
		[ 'pahrruhx', 'pārrūgs', ],
		[ 'yahß\b{wb}', 'jās', ],
		[ 'àh', 'ā', ],
		[ 'à', 'ā', ],
		[ 'ie', 'ī', ],
		[ 'ee', 'ie', ],
		[ '#', 'ie', ],
		[ 'ahy', 'āj', ],
		[ '\b{wb}tahw', 'tēw', ],
		[ '\b{wb}ahw', 'aw', ],
		[ 'swähr', 'zwēr', ],
		[ 'ſwähr', 'zwēr', ],
		[ 'ah', 'ā', ],
		[ 'äh', 'ē', ],
		[ 'ghräk', 'grēk', ],
		[ 'ällk', 'elk', ],
		[ 'cillwäk', 'cilwēk', ],
		[ 'swär', 'zwēr', ],
		[ 'yä', 'je', ],
		[ 'ä', 'e', ],
		[ 'nabbax', 'nabags', ],
		[ 'bb', 'b', ],
		[ 'dd', 'd', ],
		[ 'dſ', 'dz', ],
		[ 'ehy', 'ēj', ],
		[ 'eh', 'ē', ],
		[ 'gg', 'g', ],
		[ 'gh', 'g', ],
		[ 'gk', 'ķ', ],
		[ 'ck', 'k', ],
		[ '\b{wb}gir\b{wb}', 'jir', ],
		[ '\b{wb}gyr\b{wb}', 'jir', ],
		[ 'pills', 'pi%s', ],	# Palīgmaiņa
		[ 'pillß', 'pi%s', ],	# Palīgmaiņa
		[ 'pilla', 'pi%a', ],	# Palīgmaiņa
		[ 'pilli\b{wb}', 'pi%i', ],	# Palīgmaiņa
		[ '\b{wb}ell', 'e%', ],	# Palīgmaiņa
		[ 'stallis', 'sta%is', ],	# Palīgmaiņa
		[ 'willu', 'wi%u', ],	# Palīgmaiņa
		[ 'll', 'l', ],
		[ '\%', 'll', ],	# Palīgmaiņas novākšana
		[ 'ļļ', 'ļ', ],
		[ 'kammary', 'ka*arī', ],	# Palīgmaiņa
		[ 'mm', 'm', ],
		[ 'kamb', 'ka$', ],	# Palīgmaiņa
		[ 'dambi', 'da$i', ],	# Palīgmaiņa
		[ 'mb', 'm', ],
		[ '\$', 'mb', ],	# Palīgmaiņas novākšana
		[ '\*', 'mm', ],	# Palīgmaiņas novākšana
		[ 'm̃', 'm', ],
		[ 'nn', 'n', ],
		[ 'nņ', 'ņ', ],
		[ 'nh', 'n', ],
		[ 'ñ', 'n', ],
		[ 'oh', 'o', ],
		[ 'ſöw', 'sew', ],
		[ 'ö', 'e', ],
		[ 'pp', 'p', ],
		[ 'ph', 'p', ],
		[ 'myrrēm', 'mi*ēm', ],	# Palīgmaiņa
		[ 'rr', 'r', ],
		[ 'rŗ', 'ŗ', ],
		[ 'ry\b{wb}', 'rij', ],
		[ 'ry', 'ŗ', ],
		[ '\*', 'rr', ],	# Palīgmaiņas novākšana
		[ 'tt', 't', ],
		[ '\b{wb}the\b{wb}', 'te', ],
		[ 'he', 'ē', ],
		[ '\b{wb}thaß\b{wb}', 'tās', ],
		[ '\b{wb}tha\b{wb} ', 'tā ', ],
		[ 'th', 't', ],
		[ 'uh', 'ū', ],
		[ '\b{wb}vs', 'uz', ],
		[ '=vs', '=uz', ],
		[ '\b{wb}vhs', 'ūz', ],
		[ 'vh', 'ū', ],
		[ 'David', 'Dawid', ],
		[ 'vien', 'wien', ],
		[ 'v', 'u', ],
		[ 'ings\b{wb}', 'iņš', ],
		[ 'ing', 'iņ', ],
		[ 'ny\b{wb}', 'nī', ],
		[ 'ny', 'ņ', ],
		[ 'ſw', 'sv', ],
		[ 'sw', 'sv', ],
		[ 'waix', 'vaigs', ],
		[ 'jaw', 'jau', ],
		[ 'WJ', 'vi', ],
		[ 'w', 'v', ],
		[ '\b{wb}py', 'pi', ],
		[ '\b{wb}by\b{wb} ', 'bij ', ],
		[ '\b{wb}iß', 'iz', ],
		[ 'iß=', 'iz=', ],
		[ 'Jß', 'iz', ],
		[ 'ih', 'ī', ],
		[ 'Jh', 'ī', ],
		[ '\b{wb}beß', 'bez', ],
		[ '\b{wb}aiß', 'aiz', ],
		[ '\b{wb}ais', 'aiz', ],
		[ '\b{wb}aiſ', 'aiz', ],
		[ 'tayßne', 'taisni', ],
		[ 'ß', 's', ],
		[ 'kunx', 'kungs', ],
		[ 'draux', 'draugs', ],
		[ '\b{wb}aux', 'augs', ],
		[ '=aux', '=augs', ],
		[ 'x', 'ks', ],
		[ '\b{wb}ney\b{wb}', 'nei', ],
		[ 'ya', 'ja', ],
		[ 'yi', 'ji', ],
		[ 'yu', 'ju', ],
		[ 'ye', 'je', ],
		[ '\b{wb}tay\b{wb}', 'tai', ],
		[ 'ay', 'aj', ],
		[ 'oy', 'oj', ],
		[ 'ey', 'ej', ],
		[ 'uy', 'uj', ],
		[ 'iy', 'ij', ],
		[ 'y', 'ī', ],
		[ 'ſp', 'sp', ],
		[ 'ſt', 'st', ],
		[ 'ſk', 'sk', ],
		[ 'ſl', 'sl', ],
		[ 'ſm', 'sm', ],
		[ 'ſn', 'sn', ],
		[ 'tapſi', 'tapsi', ],
		[ 'ſ', 'z', ],
		[ 'Ꞩ', 's', ],
		[ '\b{wb}adb', 'atb', ],
		[ '\b{wb}abd', 'apd', ],
		[ 'ch', 'h', ],
		[ 'reis\b{wb}', 'reiz', ],
		[ 'gries', 'griez', ],
		[ 'Jr', 'ir', ],
		[ 'Jlga', 'ilga', ],
		[ 'lūksi', 'lūgsi', ],
		[ 'jepše', 'jebšu', ],
		[ 'gērb', 'ģērb', ],
		[ 'gelb', 'ģelb', ],
		[ 'bēkt', 'bēgt', ],
		[ 'rūkt', 'rūgt', ],
		[ 'klash', 'klās', ],
		[ 'kīl', 'ķīl', ],
		[ '\b{wb}drīs\b{wb}', 'drīz', ],
		[ 'dekt', 'degt', ],
		[ 'adod', 'atdod', ],
		[ 'atriepšanas', 'atriebšanas', ],
		[ 'pirmaķ', 'pirmāk', ],
		[ 'iezāks', 'iesāks', ],
		[ 'celš', 'ceļš', ],
		[ 'sīkssts', 'sīksts', ],
		[ 'barks', 'bargs', ],
		[ '\b{wb}mas\b{wb}', 'maz', ],
		[ 'gīm', 'ģīm', ],
		[ 'robeš', 'robež', ],
		[ 'zišanu', 'sišanu', ],
		[ 'zeptiņas', 'septiņas', ],
		[ 'zudrab', 'sudrab', ],
		[ 'vādzemes', 'vāczemes', ],
		[ 'zaltu', 'saltu', ],
		[ '\b{wb}snieks', 'sniegs', ],
		[ 'tislam', 'tizlam', ],
		[ 'saimot', 'zaimot', ],
		[ 'grāpt', 'grābt', ],
		[ 'liekt', 'liegt', ],
		[ 'cetorc', 'ceturts', ],
		[ 'kurc', 'kurts', ],
		[ 'dārks', 'dārgs', ],
		[ 'slinķis', 'sliņķis', ],
		[ 'Jk', 'ik', ],
	],
	'Manc1654_LP3' => [
		[ '\b{wb}vß', 'u&', ],	# Palīgmaiņa
		[ '\b{wb}vs', 'u&', ],	# Palīgmaiņa
		[ 'vhs', 'ū&', ],	# Palīgmaiņa
		[ 'JESV', 'Jē&u', ],	# Palīgmaiņa
		[ 'J E S V\b{wb}', 'Jē&u', ],	# Palīgmaiņa
		[ 'vh', 'ū', ],
		[ 'v', 'u', ],
		[ 'attſchki', 'atšķi', ],
		[ 'tſch', 'č', ],
		[ 'daſſch', 'daž', ],
		[ 'Ļauſſch', 'ļauž', ],
		[ 'ſſch', 'š', ],
		[ 'ghauſch', 'gauž', ],
		[ 'Brieſch', 'brīž', ],
		[ '\b{wb}muſch', 'mūž', ],
		[ 'ſchäl', 'žēl', ],
		[ 'Muiſch', 'muiž', ],
		[ 'daſch', 'daž', ],
		[ 'allaſch', 'a%až', ],	# Palīgmaiņa
		[ 'muhſch', 'mūž', ],
		[ 'Ļauſch', 'ļauž', ],
		[ 'Meſch', 'mež', ],
		[ 'ſchähl', 'žēl', ],
		[ 'Blehſch', 'blēž', ],
		[ 'ſchehl', 'žēl', ],
		[ 'ſchel', 'žēl', ],
		[ 'Ghreeſch', 'gr#ž', ],	# Palīgmaiņa
		[ 'ſpeeſch', 'sp#ž', ],	# Palīgmaiņa
		[ 'kleedſch', 'kl#dž', ],	# Palīgmaiņa
		[ 'Ghaſpaſch', 'gaspaž', ],
		[ 'ẜehſch', 'sēž', ],
		[ 'dſirrſch', 'd&irž', ],	# Palīgmaiņa
		[ 'Ahſch', 'āž', ],
		[ '\b{wb}diſch', 'diž', ],
		[ 'laiſch', 'laiž', ],
		[ 'lauſch', 'lauž', ],
		[ '\b{wb}Naſch', 'naž', ],
		[ 'ſchnau', 'žņau', ],
		[ 'gauſch', 'gauž', ],
		[ 'ghruhſch', 'grūž', ],
		[ 'ſpreeſch', 'spr#ž', ],	# Palīgmaiņa
		[ 'ſchaw', 'žāv', ],
		[ 'Meeſch', 'm#ž', ],	# Palīgmaiņa
		[ 'Papehſch', 'papēž', ],
		[ 'ẜweeſch', 'sv#ž', ],	# Palīgmaiņa
		[ 'ſpohſch', 'spož', ],
		[ 'ſieſch', '&īž', ],	# Palīgmaiņa
		[ 'ghrauſch', 'grauž', ],
		[ 'Spohſch', 'spož', ],
		[ 'ẜpohſch', 'spožs', ],
		[ 'ſchaggar', 'žagar', ],
		[ 'baſch', 'baž', ],
		[ 'Ꞩmarrſcha', 'smarž', ],
		[ 'Sieſch', '&īž', ],	# Palīgmaiņa
		[ '\b{wb}Aſch', 'āž', ],
		[ 'peepehſche', 'p#pēži', ],	# Palīgmaiņa
		[ 'Speeſch', 'sp#ž', ],	# Palīgmaiņa
		[ 'rieſch', 'rīž', ],
		[ '\b{wb}aukſch', 'augš', ],
		[ 'luhkſch', 'lūgš', ],
		[ 'Kleekſch', 'kl#gš', ],	# Palīgmaiņa
		[ 'ſchk', 'šķ', ],
		[ 'ſch', 'š', ],
		[ 'ſſ', 'š', ],
		[ 'ſẜ', 's', ],
		[ 'aiſto', 'ai&to', ],	# Palīgmaiņa
		[ 'lauſt', 'lau&t', ],	# Palīgmaiņa
		[ 'ſt', 'st', ],
		[ 'ſwehr', '&vēr', ],	# Palīgmaiņa
		[ 'ſwähr', '&vēr', ],	# Palīgmaiņa
		[ 'ſwär', '&vēr', ],	# Palīgmaiņa
		[ 'ſwer', '&vēr', ],	# Palīgmaiņa
		[ 'ſwann', '&van', ],	# Palīgmaiņa
		[ 'ſweeds', '&v#d&', ],	# Palīgmaiņa
		[ 'ſw', 'sv', ],
		[ 'ſkeet', 'šķ&t', ],	# Palīgmaiņa
		[ 'ſkie', 'šķī', ],
		[ 'ſki', 'šķi', ],
		[ 'ſk', 'sk', ],
		[ 'ſp', 'sp', ],
		[ 'wehrſ', 'vērs', ],
		[ 'ſaist', 'saist', ],
		[ 'Eſaia', 'Esaia', ],
		[ 'ſ', '&', ],	# Palīgmaiņa
		[ 'Semm', '&em', ],	# Palīgmaiņa
		[ 'Sämm', '&em', ],	# Palīgmaiņa
		[ 'Siem', '&īm', ],	# Palīgmaiņa
		[ 'Sällt', '&elt', ],	# Palīgmaiņa
		[ 'Swaig', '&vaig', ],	# Palīgmaiņa
		[ 'Sagg', '&ag', ],	# Palīgmaiņa
		[ 'Siņņ', '&iņ', ],	# Palīgmaiņa
		[ 'Sahl', '&āl', ],	# Palīgmaiņa
		[ 'Sob', '&ob', ],	# Palīgmaiņa
		[ 'Sohb', '&ob', ],	# Palīgmaiņa
		[ 'Sied', '&īd', ],	# Palīgmaiņa
		[ 'Swähr', '&vēr', ],	# Palīgmaiņa
		[ 'Siw', '&iv', ],	# Palīgmaiņa
		[ 'Sirrgh', '&irg', ],	# Palīgmaiņa
		[ 'Sirrņ', '&irņ', ],	# Palīgmaiņa
		[ 'Schäl', 'žēl', ],
		[ 'Schk', 'šķ', ],
		[ 'Schullt', 'žult', ],
		[ 'Schul', 'žul', ],
		[ 'Schaggat', 'žagat', ],
		[ 'Schohg', 'žog', ],
		[ 'Sch', 'š', ],
		[ 'Sahd\&', '&ād&', ],	# Palīgmaiņa
		[ 'Sall', '&al', ],	# Palīgmaiņa
		[ 'Snoht', '&not', ],	# Palīgmaiņa
		[ 'Swei', '&vej', ],	# Palīgmaiņa
		[ 'Saimot', '&aimot', ],	# Palīgmaiņa
		[ 'Selle', '&e%e', ],	# Palīgmaiņa
		[ 'Sem̃e', '&eme', ],	# Palīgmaiņa
		[ '\b{wb}Sinn', '&in', ],	# Palīgmaiņa
		[ 'Saļļ', '&aļ', ],	# Palīgmaiņa
		[ 'Sarrn', '&arn', ],	# Palīgmaiņa
		[ 'Sibbi', '&ibi', ],	# Palīgmaiņa
		[ 'Seed', '&#d', ],	# Palīgmaiņa
		[ 'Seck', '&eķ', ],	# Palīgmaiņa
		[ 'Sahrd', '&ārd', ],	# Palīgmaiņa
		[ 'Seem', '&#m', ],	# Palīgmaiņa
		[ 'Sagka', '&aķa', ],	# Palīgmaiņa
		[ 'dẜ', 'd&', ],	# Palīgmaiņa
		[ 'tẜch', 'č', ],
		[ 'Luhkẜch', 'lūgš', ],
		[ 'kleek', 'kl#g', ],	# Palīgmaiņa
		[ 'ẜchk', 'šķ', ],
		[ 'ẜch', 'š', ],
		[ 'ẜ', 's', ],
		[ 'Ꞩchk', 'šķ', ],
		[ 'Ꞩch', 'š', ],
		[ 'Ꞩ', 's', ],
		[ 'ohtz', 'ots', ],
		[ 'enahtz', 'enāts', ],
		[ 'inahtz', 'ināts', ],
		[ 'pehtz', 'pēc', ],
		[ 'ehtz', 'ēts', ],
		[ '\b{wb}nahtz', 'nāc', ],
		[ 'ee=sahtz', '#sāc', ],	# Palīgmaiņa
		[ 'ahtz', 'āts', ],
		[ 'ietz', 'īts', ],
		[ 'brähtz', 'brēc', ],
		[ 'lähtz', 'lēc', ],
		[ 'ähtz', 'ēts', ],
		[ 'patz', 'pats', ],
		[ 'nokautz', 'nokauts', ],
		[ 'Prowetz', 'provets', ],
		[ 'kulltz', 'kults', ],
		[ 'ruhktz', 'rūgts', ],
		[ 'licktz', 'likts', ],
		[ 'pattz', 'pats', ],
		[ 'auxtz', 'auksts', ],
		[ 'zitz', 'cits', ],
		[ 'sehtz', 'sēts', ],
		[ 'willtz', 'vilts', ],
		[ 'jämbtz', 'jemts', ],
		[ 'Ammatz', 'amats', ],
		[ 'nacktz', 'nakts', ],
		[ 'seetz', 's#ts', ],	# Palīgmaiņa
		[ 'Willtz', 'vilts', ],
		[ 'äsöhtz', 'esots', ],
		[ 'mähtatz', 'mētāts', ],
		[ 'pa=nahktz', 'panākts', ],
		[ 'salltz', 'salts', ],
		[ 'zittz', 'cits', ],
		[ 'deßmitz', 'desmits', ],
		[ 'saucktz', 'saukts', ],
		[ 'deßmittz', 'desmits', ],
		[ 'satz', 'sac', ],
		[ 'zälltz', 'celts', ],
		[ 'wätz', 'vec', ],
		[ 'Titz', 'tic', ],
		[ 'sauktz', 'saukts', ],
		[ 'smeetz', 'sm#ts', ],	# Palīgmaiņa
		[ 'smilltz', 'smilts', ],
		[ 'zeetz', 'c#ts', ],	# Palīgmaiņa
		[ 'pirrktz', 'pirkts', ],
		[ 'Raxtz', 'raksts', ],
		[ '\b{wb}Autz', 'auts', ],
		[ 'kahrtz', 'kārts', ],
		[ 'rautz', 'rauts', ],
		[ 'juhktz', 'jūgts', ],
		[ 'ghruhtz', 'grūts', ],
		[ 'Peektz', 'p#kts', ],	# Palīgmaiņa
		[ 'bagghatz', 'bagāts', ],
		[ 'racktz', 'rakts', ],
		[ 'Zättortz', 'cetorts', ],
		[ 'tz', 'c', ],
		[ 'z', 'c', ],
		[ '\&', 'z', ],	# Palīgmaiņas novākšana
		[ '\b{wb}iß', 'iz', ],
		[ 'Jß', 'iz', ],
		[ 'aißkar', 'aizskar', ],
		[ '\b{wb}aiß', 'aiz', ],
		[ '\b{wb}beß', 'bez', ],
		[ '\b{wb}ihß', 'īz', ],
		[ '\b{wb}Jhß', 'īz', ],
		[ 'ß', 's', ],
		[ '\b{wb}by', 'bij', ],
		[ '\b{wb}py', 'pi', ],
		[ 'ya', 'ja', ],
		[ 'ney', 'nei', ],
		[ 'ey', 'ej', ],
		[ 'Wuy', 'wui', ],
		[ 'y', 'ī', ],
		[ 'äh', 'ē', ],
		[ 'ghräk', 'grēk', ],
		[ 'Cillwä', 'cilvē', ],
		[ 'ädam', 'ēdam', ],
		[ 'ghribbä', 'gribē', ],
		[ 'mätt', 'met', ],
		[ 'cättort', 'cetort', ],
		[ 'cätturt', 'ceturt', ],
		[ 'ät', 'ēt', ],
		[ 'ädu', 'ēdu', ],
		[ 'Šķäp', 'šķēp', ],
		[ 'Pasläpp', 'paslēp', ],
		[ 'Bäd', 'bēd', ],
		[ 'säd', 'sēd', ],
		[ 'dzäruš', 'dzēruš', ],
		[ 'Jäcob', 'Jēkob', ],
		[ 'ä', 'e', ],
		[ 'auxt', 'augst', ],
		[ 'leex', 'l#gs', ],	# Palīgmaiņa
		[ 'behx', 'bēgs', ],
		[ 'luhx', 'lūgs', ],
		[ 'dex', 'degs', ],
		[ 'juhx', 'jūgs', ],
		[ 'slehx', 'slēgs', ],
		[ 'sprahx', 'sprāgs', ],
		[ 'x', 'ks', ],
		[ 'ie', 'ī', ],
		[ '#', 'ie', ],	# Palīgmaiņas novākšana
		[ 'ee', 'ie', ],
		[ 'Wella', 'we%a', ],	# Palīgmaiņa
		[ 'Wellu', 'we%u', ],	# Palīgmaiņa
		[ 'Welli', 'we%i', ],	# Palīgmaiņa
		[ 'Wells', 'we%s', ],	# Palīgmaiņa
		[ 'pilla', 'pi%a', ],	# Palīgmaiņa
		[ 'pillu', 'pi%u', ],	# Palīgmaiņa
		[ 'pills', 'pi%s', ],	# Palīgmaiņa
		[ 'pillà', 'pi%ā', ],	# Palīgmaiņa
		[ '\b{wb}ell', 'e%', ],	# Palīgmaiņa
		[ 'mellku', 'melku', ],
		[ 'mell', 'me%', ],	# Palīgmaiņa
		[ 'll', 'l', ],
		[ '\%', 'll', ],	# Palīgmaiņas novākšana
		[ 'bb', 'b', ],
		[ 'ck', 'k', ],
		[ 'dd', 'd', ],
		[ 'eh', 'ē', ],
		[ 'gh', 'g', ],
		[ 'gg', 'g', ],
		[ 'gir', 'jir', ],
		[ 'ah', 'ā', ],
		[ 'à', 'ā', ],
		[ 'Laihk', 'laik', ],
		[ 'ih', 'ī', ],
		[ 'jh', 'ģ', ],
		[ 'Jh ', 'ī', ],
		[ 'ļļ', 'ļ', ],
		[ 'mm', 'm', ],
		[ 'm̃', 'm', ],
		[ 'Augstamba', 'Augsta$a', ],	# Palīgmaiņa
		[ 'Kamba', 'Ka$a', ],	# Palīgmaiņa
		[ 'Damb', 'Da$', ],	# Palīgmaiņa
		[ 'mb', 'm', ],
		[ '\$', 'mb', ],	# Palīgmaiņas novākšana
		[ 'ñ', 'n', ],
		[ 'nh', 'n', ],
		[ 'nn', 'n', ],
		[ 'ings', 'iņš', ],
		[ 'ing', 'iņ', ],
		[ 'w', 'v', ],
		[ 'nj', 'ņ', ],
		[ '\b{wb}kon', 'ķēn', ],
		[ 'oh', 'o', ],
		[ 'ö', 'e', ],
		[ 'th', 't', ],
		[ 'tt', 't', ],
		[ 'uh', 'ū', ],
		[ 'rr', 'r', ],
		[ 'appil', 'aΔil', ],	# Palīgmaiņa
		[ 'appūšķ', 'aΔūšķ', ],	# Palīgmaiņa
		[ 'pp', 'p', ],
		[ 'aΔil', 'appil', ],	# Palīgmaiņas novākšana
		[ 'aΔūšķ', 'appūšķ', ],	# Palīgmaiņas novākšana
		[ 'Chr', 'Kr', ],
		[ 'ch', 'h', ],
		[ 'aiskar', 'aizskar', ],
		[ 'aiskār', 'aizskār', ],
		[ 'aislēdz', 'aizslēdz', ],
		[ '\b{wb}ais', 'aiz', ],
		[ 'zlēkt', 'slēgt', ],
		[ 'līds', 'līdz', ],
		[ 'sūds', 'sūdz', ],
		[ 'dauds', 'daudz', ],
		[ 'reds', 'redz', ],
		[ 'beids', 'beidz', ],
		[ 'lūds', 'lūdz', ],
		[ 'neds', 'nedz', ],
		[ 'lieds', 'liedz', ],
		[ 'Drauds', 'draudz', ],
		[ 'bēds', 'bēdz', ],
		[ '\b{wb}uss', 'uzs', ],
		[ '\b{wb}ūss', 'ūzs', ],
		[ '\b{wb}iss', 'izs', ],
		[ 'passau', 'pasau', ],
		[ 'klauss', 'klaus', ],
		[ 'mūss', 'mūs', ],
		[ 'kļūss', 'kļūs', ],
		[ 'zemessoj', 'zemessoģ', ],
		[ 'gk', 'ķ', ],
		[ 'ŗŗ', 'ŗ', ],
		[ 'VIz', 'vis', ],
		[ 'jav', 'jau', ],
		[ 'Jrbal', 'Irbal', ],
		[ '\b{wb}rūkt', 'rūgt', ],
		[ 'lūkt', 'lūgt', ],
		[ 'ņņ', 'ņ', ],
		[ '\b{wb}us', 'uz', ],
		[ 'qu', 'kv', ],
		[ 'kļua', 'kļuva', ],
		[ '\b{wb}enaidn', 'ienaidn', ],
		[ 'eẽ', 'iem', ],
		[ 'nņ', 'ņ', ],
		[ 'ã', 'am', ],
		[ 'adb', 'atb', ],
		[ 'jk', 'ik', ],
		[ 'KRJ', 'kri', ],
		[ 'C H R J S T J', 'KRISTI', ],
		[ 'Jzrael', 'Izrael', ],
		[ 'kriSTJ', 'KRISTI', ],
		[ 'MJe', 'mī', ],
		[ 'Jr', 'Ir', ],
		[ 'E L J', 'Eli', ],
		[ 'Jzop', 'Izop', ],
		[ 'Jzaac', 'Īzak', ],
		[ 'Jš', 'Iš', ],
		[ 'Jac', 'Jak', ],
		[ 'drīs\b{wb}', 'drīz', ],
		[ 'Dārs', 'dārz', ],
		[ 'oe', 'e', ],
	],
	'Meg1593_PN'  => [
		[ '\b{wb}Mus\b{wb}', 'Mūs', ],
		[ '\b{wb}tab', 'tēv', ],
		[ '\b{wb}eckſch', 'iekš', ],
		[ '\b{wb}ekaksch', 'iekš', ],
		[ 'bess', 'es', ],
		[ '\b{wb}ſchvvetitz\b{wb}', 'švētīts', ],
		[ '\b{wb}tou', 'tav', ],
		[ 'vaartz\b{wb}', 'ārds', ],
		[ '\b{wb}enac', 'ienā', ],
		[ 'ovv', 'av', ],
		[ 'valſti', 'alstī', ],
		[ 'aatz\b{wb}', 'āts', ],
		[ '\b{wb}bus\b{wb}', 'būs', ],
		[ '\b{wb}ka\b{wb}', 'kā', ],
		[ 'bb', 'b', ],
		[ '\b{wb}ta\b{wb}', 'tā', ],
		[ 'vrſ', 'irs', ],
		[ '\b{wb}ſem', 'ze', ],
		[ '\b{wb}muſſ', 'mūs', ],
		[ '\b{wb}deniſche\b{wb}', 'dieniske', ],
		[ '\b{wb}maiſ', 'maiz', ],
		[ '\b{wb}duth\b{wb}', 'dot', ],
		[ '\b{wb}ſchodeẽ\b{wb}', 'šodien', ],
		[ 'mma', 'me', ],
		[ '\b{wb}mũs\b{wb}', 'mūs', ],
		[ '\b{wb}gra', 'grē', ],
		[ '\b{wb}mess\b{wb}', 'mēs', ],
		[ '\b{wb}pãmart\b{wb}', 'pame', ],
		[ 'radvekẽ\b{wb}', 'ādnieken', ],
		[ '\b{wb}euued', 'ieve', ],
		[ '\b{wb}lo', 'ļa', ],
		[ '\{jo', '{ja', ],
		[ 'ck', 'k', ],
		[ '\b{wb}pett\b{wb}', 'bet', ],
		[ '\b{wb}paſſ', 'pas', ],
		[ '\b{wb}nu\b{wb}', 'no', ],
		[ '\b{wb}vvuſſe\b{wb}', 'vise', ],
		[ '\{iou', '{ja', ],
		[ 'Amen', 'Āmen', ],
	],
	'Reit1675_OD' => [
		[ 'muuſch', 'mūž', ],
		[ 'ſch', 'š', ],
		[ 'Maiſ', 'maiz', ],
		[ 'ſ', 's', ],
		[ 'ää', 'ē', ],
		[ 'Täwß', 'tēvs', ],
		[ 'Swät', 'svēt', ],
		[ 'kiän', 'ķēn', ],
		[ '\b{wb}mäß', 'mēs', ],
		[ 'kärdin', 'kārdin', ],
		[ 'kän', 'ķēn', ],
		[ 'ä', 'e', ],
		[ 'ß', 's', ],
		[ 'dz', 'ds', ],
		[ 'tz', 'ts', ],
		[ 'y', 'i', ],
		[ 'iaw', 'jau', ],
		[ 'w', 'v', ],
		[ 'li', 'ļ', ],
		[ 'bb', 'b', ],
		[ 'mm', 'm', ],
		[ 'tt', 't', ],
		[ 'dd', 'd', ],
		[ 'uu', 'ū', ],
		[ 'ee', 'ie', ],
		[ 'oo', 'o', ],
		[ 'aa', 'ā', ],
		[ 'Sem', 'zem', ],
		[ 'den', 'dien', ],
		[ 'MŪso', 'mūsu', ],
	],
	'Reit1675_UeP' => [
		[ 'wingſch', 'viņš', ],
		[ 'ſchäl', 'žēl', ],
		[ 'laiſch', 'laiž', ],
		[ 'ſpeeſch', 'spiež', ],
		[ 'Muuſch', 'mūž', ],
		[ 'muſch', 'mūž', ],
		[ 'allaſch', 'a%až', ],	# Palīgmaiņa
		[ 'ſch', 'š', ],
		[ 'dſ', 'd#', ],	# Palīgmaiņa
		[ 'Moſ', 'Mo#', ],	# Palīgmaiņa
		[ 'Aiſto', 'Ai#to', ],	# Palīgmaiņa
		[ 'Noſeeg', 'no#ieg', ],	# Palīgmaiņa
		[ 'ſakt', '#agt', ],	# Palīgmaiņa
		[ 'Äſälj', 'ē#eļ', ],	# Palīgmaiņa
		[ 'ſämm', '#em', ],	# Palīgmaiņa
		[ 'Jeſ', 'Jē#', ],	# Palīgmaiņa
		[ 'maſſ', 'ma#', ],	# Palīgmaiņa
		[ '\b{wb}aiſ', 'ai#', ],	# Palīgmaiņa
		[ 'Phariſ', 'fari#', ],	# Palīgmaiņa
		[ 'Baſnitz', 'ba#nīc', ],	# Palīgmaiņa
		[ 'ſuud', '#ūd', ],	# Palīgmaiņa
		[ 'ſwär', '#vēr', ],	# Palīgmaiņa
		[ 'Jeruſ', 'Jeru#', ],	# Palīgmaiņa
		[ 'greeſ', 'grie#', ],	# Palīgmaiņa
		[ 'ſiñ', '#in', ],	# Palīgmaiņa
		[ 'ſinn', '#in', ],	# Palīgmaiņa
		[ 'Maiſ', 'mai#', ],	# Palīgmaiņa
		[ 'maſ\b{wb}', 'ma#', ],	# Palīgmaiņa
		[ 'maſg', 'ma#g', ],	# Palīgmaiņa
		[ 'ſoog', '#og', ],	# Palīgmaiņa
		[ 'ſuš', '#uš', ],	# Palīgmaiņa
		[ 'paſy', 'pa#ī', ],	# Palīgmaiņa
		[ 'paſit', 'pa#īt', ],	# Palīgmaiņa
		[ 'gaſ', 'gā#', ],	# Palīgmaiņa
		[ 'gaaſ', 'gā#', ],	# Palīgmaiņa
		[ 'graiſ', 'grai#', ],	# Palīgmaiņa
		[ 'ſkee', 'šķie', ],
		[ 'ſki', 'šķi', ],
		[ 'ſky', 'šķī', ],
		[ 'ſia', 'ša', ],
		[ 'raiſ', 'rai#', ],	# Palīgmaiņa
		[ 'ſſ', 's', ],
		[ 'ſ', 's', ],
		[ 'täitz', 'teic', ],
		[ 'itz\b{wb}', 'īts', ],
		[ 'dätz\b{wb}', 'dēts', ],
		[ 'swätz\b{wb}', 'svēts', ],
		[ 'Praatz', 'prāts', ],
		[ 'tärptz', 'tērpts', ],
		[ 'liktz', 'likts', ],
		[ 'sauktz', 'saukts', ],
		[ 'mästz', 'mests', ],
		[ 'Swätitz', 'svētīts', ],
		[ 'Rytz', 'rīts', ],
		[ 'maritz', 'mērīts', ],
		[ 'dootz', 'dots', ],
		[ 'wärtz', 'vērts', ],
		[ 'Tziusk', 'čūsk', ],
		[ 'platz', 'plats', ],
		[ 'tzirstz', 'cirsts', ],
		[ 'lid#inatz', 'līd#ināts', ],	# Palīgmaiņas dalība
		[ 'pästitz', 'pestīts', ],
		[ 'ttz', 'c', ],
		[ 'tz', 'c', ],
		[ 'ddz', 'd#', ],
		[ 'Wardz', 'vārds', ],
		[ 'Goodz', 'gods', ],
		[ 'Sirdz', 'sirds', ],
		[ 'dz', 'd#', ],	# Palīgmaiņa
		[ 'z', 'c', ],
		[ '#', 'z', ],	# Palīgmaiņas novākšana
		[ '\b{wb}iß', 'iz', ],
		[ '\b{wb}uß', 'uz', ],
		[ '\b{wb}uuß', 'ūz', ],
		[ 'Jß', 'iz', ],
		[ 'ß', 's', ],
		[ 'ää', 'ē', ],
		[ 'ädam', 'ēdam', ],
		[ 'Täw', 'tēv', ],
		[ 'Bärn', 'bērn', ],
		[ 'Schäl', 'žēl', ],
		[ '\b{wb}Nä', 'ne', ],
		[ 'trumpät', 'trumpet', ],
		[ 'ätt', 'et', ],
		[ 'ät', 'ēt', ],
		[ 'dusä', 'dusē', ],
		[ 'päc', 'pēc', ],
		[ 'Cilwäk', 'cilvēk', ],
		[ 'myläj', 'mīlēj', ],
		[ 'Dwäs', 'dvēs', ],
		[ 'pawälj', 'pavēļ', ],
		[ 'släpt', 'slēpt', ],
		[ 'Kiän', 'ķēn', ],
		[ 'rädzä', 'redzē', ],
		[ 'Jäbb', 'jeb', ],
		[ 'iä\b{wb}', 'ja', ],
		[ 'Jä\b{wb}', 'ja', ],
		[ 'Äka', 'ēka', ],
		[ 'dzirdäi', 'dzirdēj', ],
		[ 'kamär', 'kamēr', ],
		[ 'cärt', 'cērt', ],
		[ 'minnäs', 'minēs', ],
		[ 'apsädas', 'apsēdās', ],
		[ 'apgräcinas', 'apgrēcinas', ],
		[ '\b{wb}bäs\b{wb}', 'bez', ],
		[ 'Swäräšan', 'zvērēšan', ],
		[ 'Kräslis', 'krēslis', ],
		[ 'slädz', 'slēdz', ],
		[ 'eenidäs', 'ienīdēs', ],
		[ 'myläs', 'mīlēs', ],
		[ 'paturräs', 'paturēs', ],
		[ 'ädis', 'ēdīs', ],
		[ 'Dräb', 'drēb', ],
		[ 'bäda', 'bēdā', ],
		[ 'Pukkiäm', 'puķēm', ],
		[ 'wärp', 'vērp', ],
		[ 'tärp', 'tērp', ],
		[ '\b{wb}mäs\b{wb}', 'mēs', ],
		[ 'mäklä', 'meklē', ],
		[ 'Pärläs', 'pērles', ],
		[ 'Klauwä', 'klauvē', ],
		[ 'wäl\b{wb}', 'vēl', ],
		[ 'gaiäju', 'gājēju', ],
		[ 'pläsigi', 'plēsīgi', ],
		[ 'Ärcsim', 'ērcsim', ],
		[ 'Wardä', 'vārdā', ],
		[ 'Äku', 'ēku', ],
		[ 'gāzäs', 'gāzēs', ],
		[ 'Turräšana', 'turēšana', ],
		[ 'späy', 'spēj', ],
		[ 'Dähls', 'dēls', ],
		[ 'ä', 'e', ],
		[ 'w', 'v', ],
		[ 'iee', 'jie', ],
		[ 'ee', 'ie', ],
		[ 'rria', 'ŗa', ],
		[ 'ria', 'ŗa', ],
		[ 'ngia', 'ņa', ],
		[ 'llia', 'ļa', ],
		[ 'lia', 'ļa', ],
		[ 'nia', 'ņa', ],
		[ 'kia', 'ķa', ],
		[ 'gia', 'ģa', ],
		[ 'ia', 'ja', ],
		[ 'lliu', 'ļu', ],
		[ 'liu', 'ļu', ],
		[ 'lju', 'ļu', ],
		[ 'Skiungios', 'šķūņos', ],
		[ 'ngiu', 'ņu', ],
		[ 'rriu', 'ŗu', ],
		[ 'riu', 'ŗu', ],
		[ 'iu', 'ju', ],
		[ 'ngio', 'ņu', ],
		[ 'llio', 'ļo', ],
		[ 'lio', 'ļo', ],
		[ 'rrgio', 'ŗo', ],
		[ 'io', 'ju', ],
		[ 'egj', 'ēj', ],
		[ 'ngi', 'ņi', ],
		[ 'Evaņiļuma', 'Evangiliuma', ],
		[ 'aa', 'ā', ],
		[ 'uu', 'ū', ],
		[ '\b{wb}ūs', 'ūz', ],
		[ 'oo', 'o', ],
		[ 'nn', 'n', ],
		[ 'dd', 'd', ],
		[ 'mm', 'm', ],
		[ '\b{wb}sem', 'zem', ],
		[ 'bb', 'b', ],
		[ 'nņ', 'ņ', ],
		[ 'pp', 'p', ],
		[ 'rr', 'r', ],
		[ 'tt', 't', ],
		[ 'ö', 'e', ],
		[ 'ya', 'ija', ],
		[ 'lay', 'lai', ],
		[ 'tay', 'tai', ],
		[ 'ey', 'ej', ],
		[ 'biy', 'bij', ],
		[ 'y', 'ī', ],
		[ 'kk', 'k', ],
		[ 'Sagglgi', 'zagļi', ],
		[ 'gg', 'g', ],
		[ 'ñ', 'n', ],
		[ 'vn', 'un', ],
		[ 'jav', 'jau', ],
		[ 'ph', 'f', ],
		[ 'Ch', 'k', ],
		[ 'à', 'ā', ],
		[ 'Elle', 'E%e', ],	# Palīgmaiņa
		[ 'mella', 'me%a', ],	# Palīgmaiņa
		[ 'pillu', 'pi%u', ],	# Palīgmaiņa
		[ 'Vell', 'Ve%', ],	# Palīgmaiņa
		[ 'll', 'l', ],
		[ '\%', 'll', ],	# Palīgmaiņas novākšana
		[ 'ã', 'an', ],
		[ 'Gijm', 'ģīm', ],
		[ 'aukš', 'augš', ],
		[ 'Seme', 'zeme', ],
		[ 'Ienij', 'Ienī', ],
		[ 'Mijl', 'Mīl', ],
		[ 'aiem', 'ajiem', ],
		[ 'Sirg', 'zirg', ],
		[ '\b{wb}us', 'uz', ],
		[ 'Sņaukta', 'zņaugta', ],
		[ 'dauds', 'daudz', ],
		[ 'neds', 'nedz', ],
		[ 'jūso', 'jūsu', ],
		[ '\b{wb}ais', 'aiz', ],
		[ 'Rags', 'raks', ],
		[ 'ck', 'k', ],
		[ 'm̃', 'm', ],
		[ 'drīs', 'drīz', ],
		[ 'sob', 'zob', ],
		[ 'gries', 'griez', ],
		[ 'ņiemt', 'ņemt', ],
		[ 'vings', 'viņš', ],
		[ 'vv', 'v', ],
		[ 'ņim', 'ngim', ],
		[ 'Devam', 'dievam', ],
		[ '\b{wb}Sali', 'zāli', ],
		[ '\b{wb}Mas', 'maz', ],
		[ '\b{wb}is', 'iz', ],
		[ 'Klauest', 'klauvēt', ],
		[ 'Siv', 'ziv', ],
		[ 'Jk', 'Ik', ],
		[ 'Vegi', 'vēji', ],
		[ 'uh', 'ū', ],
		[ 'th', 't', ],
		[ '\b{wb}Sin', 'zin', ],
		[ 'šh', 'š', ],
		[ 'ẽ', 'em', ],
	],
	'Thev1575_PN' => [
		[ '\b{wb}MVs\b{wb}', 'MŪs', ],
		[ '\b{wb}tab', 'tēv', ],
		[ '\b{wb}eckſc', 'iekš', ],
		[ 'bb', 'b', ],
		[ 'ßis\b{wb}', 'sis', ],
		[ '\b{wb}ſchuuetitz\b{wb}', 'švētīts', ],
		[ '\b{wb}tuos\b{wb}', 'tavs', ],
		[ 'uaartz\b{wb}', 'ārds', ],
		[ '\b{wb}Enac', 'Ienā', ],
		[ '\b{wb}touus\b{wb}', 'tavs', ],
		[ 'ualſ', 'alstī', ],
		[ 'aatz\b{wb}', 'āts', ],
		[ '\b{wb}bus\b{wb}', 'būs', ],
		[ '\b{wb}ka\b{wb}', 'kā', ],
		[ '\b{wb}ta\b{wb}', 'tā', ],
		[ '\b{wb}ekaksch', 'iekš', ],
		[ '\b{wb}vurſ', 'virs', ],
		[ '\b{wb}ſem', 'ze', ],
		[ '\b{wb}Muſſ', 'Mūs', ],
		[ '\b{wb}deniſch', 'dienisk', ],
		[ 'iſe\b{wb}', 'ize', ],
		[ '\b{wb}duth\b{wb}', 'dot', ],
		[ '\b{wb}ſchode', 'šodi', ],
		[ 'mat', 'et', ],
		[ '\b{wb}muſſ', 'mūs', ],
		[ '\b{wb}gra', 'grē', ],
		[ '\b{wb}meß\b{wb}', 'mēs', ],
		[ 'mar', 'e', ],
		[ 'radu', 'ādni', ],
		[ '\b{wb}euued', 'ieve', ],
		[ '\b{wb}lou', 'ļau', ],
		[ '\{io', 'ja', ],
		[ 'ck', 'k', ],
		[ '\b{wb}pett\b{wb}', 'bet', ],
		[ 'ſſa', 'sa', ],
		[ '\b{wb}nu\b{wb}', 'no', ],
		[ 'uuſſ', 'is', ],
		[ '\b{wb}Amen\b{wb}', 'Āmen', ],
	],
};

our $TABLES_Apokr1689 = {};

our $TABLES_JT1685 = {};

our $TABLES_VD1689_94 = {};

sub substTable
{
	my $tableName = shift @_;
	my $collection = shift @_;
	return $TABLES_SINGLES->{$tableName} unless ($collection);
	return $TABLES_Apokr1689->{$tableName} if ($collection =~ /\s*Apokr1689\s*/);
	return $TABLES_JT1685->{$tableName} if ($collection =~ /\s*JT1685\s*/);
	return $TABLES_VD1689_94->{$tableName} if ($collection =~ /\s*VD1689_94\s*/);
	return $TABLES_SINGLES->{$tableName};
}

sub hasTable
{
	my $tableName = shift @_;
	my $collection = shift @_;
	return exists $TABLES_SINGLES->{$tableName} unless ($collection);
	return exists $TABLES_Apokr1689->{$tableName} if ($collection =~ /\s*Apokr1689\s*/);
	return exists $TABLES_JT1685->{$tableName} if ($collection =~ /\s*JT1685\s*/);
	return exists $TABLES_VD1689_94->{$tableName} if ($collection =~ /\s*VD1689_94\s*/);
	return exists $TABLES_SINGLES->{$tableName};
}

1;